### ISSUE TITLE
Падение Fatal Exception: java.lang.AssertionError после обновления SDK яндекс рекламы до версии 4.2.0

### ISSUE THREAD

**Issue by Ilik777** [yandexmobile/yandex-ads-sdk-android#100]
После обновления com.yandex.android:mobileads до версии 4.2.0 появились падения на Android 8.1.0
За последние 7 дней было 15 падений, все девайсы версии Android 8.1.0
Падение не вспроизводится.

`Fatal Exception: java.lang.AssertionError: No NameTypeIndex match for SHORT_STANDARD
       at android.icu.impl.TimeZoneNamesImpl$ZNames.getNameTypeIndex(TimeZoneNamesImpl.java:724)
       at android.icu.impl.TimeZoneNamesImpl$ZNames.getName(TimeZoneNamesImpl.java:790)
       at android.icu.impl.TimeZoneNamesImpl.getTimeZoneDisplayName(TimeZoneNamesImpl.java:183)
       at android.icu.text.TimeZoneNames.getDisplayName(TimeZoneNames.java:261)
       at java.text.SimpleDateFormat.subFormat(SimpleDateFormat.java:1296)
       at java.text.SimpleDateFormat.format(SimpleDateFormat.java:1004)
       at java.text.SimpleDateFormat.format(SimpleDateFormat.java:974)
       at java.text.DateFormat.format(DateFormat.java:341)
       at org.apache.http.impl.cookie.DateUtils.formatDate(DateUtils.java:206)
       at org.apache.http.impl.cookie.DateUtils.formatDate(DateUtils.java:185)
       at com.yandex.mobile.ads.impl.avg.a(SourceFile:1232)
       at com.yandex.mobile.ads.impl.auq.run(SourceFile:122)
`

Как я понимаю баг есть только на Android 8.1.0 и в интернете советуют добавить обработку ошибок, чтобы измежать ошибок.

`
try {
            TimeZone tz = TimeZone . getDefault ();
            deviceTimezoneAbbreviation = tz.getDisplayName(
                    tz.inDaylightTime(new Date ()),
                    TimeZone.SHORT
            );
            deviceTimeZoneName = tz.getID();
        } catch (AssertionError e) {
            // Workaround for a bug in Android that can cause crashes on Android 8.0 and 8.1
        } catch (Exception e) {
        }
`

Нашел несколько похожих случаев в интернете
https://github.com/google/volley/issues/177

https://stackoverflow.com/questions/51453091/android-facebook-sdk-internal-utility-java-lang-assertionerror/52035884#52035884

https://issuetracker.google.com/issues/110848122?pli=1

**Comment by Nikitapls** [comment]
Добрый день.
Спасибо за подробное описание, взяли в работу.

**Comment by mobile-ads-github** [comment]
Добрый день.
Спасибо за подробный фидбек, приняли в работу.

**Comment by mobile-ads-github** [comment]
Добрый день, исправили проблему в релизе 4.4.0.
