### ISSUE TITLE
Резко увеличилось количество ANR

### ISSUE THREAD

**Issue by AmanzholT** [yandexmobile/yandex-ads-sdk-android#127]
После обновления на версию 5.0.0 наблюдаем резкое увеличение логов по ANR в крашлитике на Android 11-12. Происходят при вызове методов 
com.yandex.mobile.ads.banner.BannerAdView.destroy
com.yandex.mobile.ads.nativeads.NativeAdLoader.cancelLoading

`
com.yandex.mobile.ads.impl.p0.a (SourceFile:7)
com.yandex.mobile.ads.core.initializer.e.a (SourceFile:3)
com.yandex.mobile.ads.nativeads.n.t (SourceFile:2)
com.yandex.mobile.ads.nativeads.p.a (SourceFile:6)
com.yandex.mobile.ads.nativeads.o.a (SourceFile:41)
com.yandex.mobile.ads.nativeads.NativeAdLoader.cancelLoading (SourceFile:1)
`

`
com.yandex.mobile.ads.impl.p0.a (SourceFile:7)
com.yandex.mobile.ads.core.initializer.e.a (SourceFile:3)
com.yandex.mobile.ads.base.p.c (SourceFile:24)
com.yandex.mobile.ads.impl.z70.c (SourceFile:1)
com.yandex.mobile.ads.impl.b71.c (SourceFile:3)
com.yandex.mobile.ads.banner.k.c (SourceFile:1)
com.yandex.mobile.ads.banner.b.c (SourceFile:27)
com.yandex.mobile.ads.banner.b.z (SourceFile:2)
com.yandex.mobile.ads.banner.g.destroy (SourceFile:2)
com.yandex.mobile.ads.banner.BannerAdView.destroy (SourceFile:1)
`

методы эти вызываем в onDestroy()

**Comment by Nazym-qa** [comment]
Такая же проблема(((

**Comment by mobile-ads-github** [comment]
Добрый день. Спасибо за репорт. О проблеме знаем - разбираемся.

**Comment by OlegTarashkevich** [comment]
Сегодня планировали опубликовать приложение с новой sdk v.5.0. Думаю проверю, все ли нормально в issues.
Оказалось придется откатиться обратно до v.4.5.

**Comment by NikiHard** [comment]
У меня вот такое при загрузке межстраничной рекламы
```
    java.lang.RuntimeException: Bad URL 
        at com.yandex.mobile.ads.impl.xa.a(SourceFile:125)
        at com.yandex.mobile.ads.impl.bq0.a(SourceFile:58)
        at com.yandex.mobile.ads.impl.bq0.run(SourceFile:4)
     Caused by: java.net.MalformedURLException: no protocol: 
        at java.net.URL.<init>(URL.java:601)
        at java.net.URL.<init>(URL.java:498)
        at java.net.URL.<init>(URL.java:447)
        at com.yandex.mobile.ads.impl.t80.a(SourceFile:13)
        at com.yandex.mobile.ads.impl.zj0.a(SourceFile:13)
        at com.yandex.mobile.ads.impl.s80.a(SourceFile:7)
        at com.yandex.mobile.ads.impl.xa.a(SourceFile:10)
        at com.yandex.mobile.ads.impl.bq0.a(SourceFile:58) 
        at com.yandex.mobile.ads.impl.bq0.run(SourceFile:4) 
```

**Comment by mobile-ads-github** [comment]
Добрый день! Да, в версии 5.1.0 исправляли ANR.
