### ISSUE TITLE
AppMetrica removal

### ISSUE THREAD

**Issue by OlegTarashkevich** [yandexmobile/yandex-ads-sdk-android#129]
Пожалуйста откажитесь от зависимости AppMetrica. От нее одни проблемы. Понимаю, что разработчики не решают, но передайте менеджерам. Если петицию начать собирать на change.org это решит вопрос?
Почему это важно? Потому, что хочется заниматься только своим кодом в приложении. Или максимум проверить как работает Yandex ad sdk с приложением. **Но проверять работоспособность зависимости sdk это уже перебор!**

Обновил версию sdk 5.0.0 & appmetrica 4.1.1
Планировался релиз приложения. Обнаружились ANR. Успели откатить версию до sdk 4.5.0 & appmetrica 4.0.0
А если бы опубликовали приложение, а потом откатились до предыдущей версии была бы следующая ошибка:

2022-04-21 13:29:04.339 2356-2578/PACKAGE_NAME W/AppMetrica: [PACKAGE_NAME] : [] Could not get writable database /data/user/0/PACKAGE_NAME/no_backup/db_metrica_ PACKAGE_NAME_60689a17-fa80-5b76-b4db-0f5151f23180 due to an exception. AppMetrica SDK may behave unexpectedly.
2022-04-21 13:29:04.341 2356-2445/PACKAGE_NAME E/AppMetrica: [PACKAGE_NAME] : [] 
    android.database.sqlite.SQLiteException: Can't downgrade database from version 100 to 97
        at android.database.sqlite.SQLiteOpenHelper.onDowngrade(SQLiteOpenHelper.java:540)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:414)
        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:316)
        at com.yandex.metrica.impl.ob.tf.getWritableDatabase(SourceFile:1)
        at com.yandex.metrica.impl.ob.qf.g(SourceFile:4)
        at com.yandex.metrica.impl.ob.qf.b(SourceFile:2)
        at com.yandex.metrica.impl.ob.qf.a(SourceFile:80)
        at com.yandex.metrica.impl.ob.ub.b(SourceFile:13)
        at com.yandex.metrica.impl.ob.ub.a(SourceFile:10)
        at com.yandex.metrica.impl.ob.ub.a(SourceFile:1)
        at com.yandex.metrica.impl.ob.ec.a(SourceFile:16)
        at com.yandex.metrica.impl.ob.ec.d(SourceFile:16)
        at com.yandex.metrica.impl.ob.ec.c(SourceFile:1)
        at com.yandex.metrica.impl.ob.b8.b(SourceFile:1)
        at com.yandex.metrica.impl.ob.la.a(SourceFile:1)
        at com.yandex.metrica.impl.ob.o9$a.a(SourceFile:2)
        at com.yandex.metrica.impl.ob.o9$a.a(SourceFile:1)
        at com.yandex.metrica.impl.ob.h9.a(SourceFile:7)
        at com.yandex.metrica.impl.ob.o9.b(SourceFile:1)
        at com.yandex.metrica.impl.ob.k7.a(SourceFile:12)
        at com.yandex.metrica.impl.ob.y7.a(SourceFile:11)
        at com.yandex.metrica.impl.ob.u8.b(SourceFile:1)
        at com.yandex.metrica.impl.ob.h8.a(SourceFile:1)
        at com.yandex.metrica.impl.ob.p4.run(SourceFile:24)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.os.HandlerThread.run(HandlerThread.java:67)

Будет ли работать Yandex ad sdk если убрать appmetrica принудительно?
Или нужно переписывать часть sdk? Если Вы не хотите переписывать, можно ли найти исходники sdk без обфускации?
Если исходников sdk нету, можно ли мне сделать reverse engineering и переписать часть логики. Повлияет ли это на показы рекламы или прибыль? Есть ли какая-то скрытая проверка целостности sdk?

**Comment by mobile-ads-github** [comment]
Добрый день.

AppMetrica необходима для корректной работы рекламного SDK. AppMetrica соблюдает стандартны безопасности данных. Существование, логика и принципы работы платформы соответсвуют политикам Google Play и App Store.

По поводу вашей проблемы с невозможностью откатить AppMetrica на старую версию: она решена для версий 4.2.0 и выше (https://appmetrica.yandex.ru/docs/mobile-sdk-dg/concepts/android-history.html#v-4-2-0). Вы можете обновиться до AppMetrica 4.2.0, после чего откаты станут безопасными в плане сохранности данных.

**Comment by OlegTarashkevich** [comment]
Хорошо, совместима ли AppMetrica 4.2.0 с рекламным SDK 4.5?

Понимаю, что она нужна рекламному sdk. Но она генерирует проблемы, не связанные с ним. Теряется время и прибыль.

**Comment by XJIOP** [comment]
Как отключить метрику? В приложении есть покупка премиум для отключения рекламы, рекламу отключаю а метрика висит со своим сервисом...
