### ISSUE TITLE
NullPointerException at com.yandex.mobile.ads.g.e.e (SourceFile:1082)

### ISSUE THREAD

**Issue by DimaKoz** [yandexmobile/yandex-ads-sdk-android#13]
Добрый день.
Получил крешлог. Эти падения единичные, рута на устройствах не обнаружено.
Пока происходит только на устройствах с андроидом 4.4.2

В проекте используется :
com.yandex.android:mobmetricalib:2.73
com.yandex.android:mobileads:2.60

Fatal Exception: java.lang.NullPointerException
       at android.os.Parcel.readException(Parcel.java:1478)
       at android.os.Parcel.readException(Parcel.java:1426)
       at android.os.storage.IMountService$Stub$Proxy.mkdirs(IMountService.java:769)
       at android.app.ContextImpl.ensureDirsExistOrFilter(ContextImpl.java:2628)
       at android.app.ContextImpl.getExternalCacheDirs(ContextImpl.java:1258)
       at android.app.ContextImpl.getExternalCacheDir(ContextImpl.java:1247)
       at android.content.ContextWrapper.getExternalCacheDir(ContextWrapper.java:247)
       at com.yandex.mobile.ads.g.e.e(SourceFile:1082)
       at com.yandex.mobile.ads.g.e.a(SourceFile:59)
       at com.yandex.mobile.ads.ao.a(SourceFile:37)
       at com.yandex.mobile.ads.ap.a(SourceFile:1054)
       at com.yandex.mobile.ads.t.a(SourceFile:7122)
       at com.yandex.mobile.ads.t$1.run(SourceFile:115)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)

**Comment by satsakul** [comment]
Спасибо за предоставленную информацию. Проблему локализовали. 
Завели задачу на исследование данной проблемы.

**Comment by satsakul** [comment]
Добрый день. Вышел релиз версии 2.70, в которой проблема была устранена. Спасибо
