### ISSUE TITLE
NullPointerException at com.yandex.mobile.ads.impl.yr

### ISSUE THREAD

**Issue by Natalie-Gaidideeva** [yandexmobile/yandex-ads-sdk-android#143]
Version 5.0.0, on application start after application update (library update from 2.180 to 5.0.0)

java.lang.Error: java.lang.NullPointerException
at java.util.Objects.requireNonNull(Objects.java:220)
at com.yandex.mobile.ads.impl.yr$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:6)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)

**Comment by mobile-ads-github** [comment]
Добрый день, спасибо за обращение
Разбираемся

**Comment by mobile-ads-github** [comment]
Добрый день, подскажите пожалуйста Application ID и версию приложения в котором происходит крэш. Как часто возникает крэш по аналитике? По возможности пришлите полный отчёт об крэше из системы аналитики на почту [mobile-ads-github@yandex-team.ru](mailto:mobile-ads-github@yandex-team.ru)

**Comment by mobile-ads-github** [comment]
Добрый день, не удалось воспроизвести проблему без дополнительной информации. Если проблема продолжает воспроизводиться, пришлите пожалуйста дополнительную информацию на почту mobile-ads-github@yandex-team.ru
