### ISSUE TITLE
В логах java.lang.RuntimeException: Bad URL at com.yandex.mobile.ads.impl.ab.a(SourceFile:125) (mobileads:5.1.1)

### ISSUE THREAD

**Issue by DimaKoz** [yandexmobile/yandex-ads-sdk-android#144]
Добрый день.

Использую :
com.yandex.android:mobmetricalib:4.2.0
com.yandex.android:mobileads:5.1.1

Иногда вижу в логах, хотя не падает и рекламу отображает:

```
2022-07-05 14:21:12.411 25945-28094 D/Yandex Mobile Ads: [253270] bs0.a: HTTP response for request=<[ ] https://an.yandex.ru/tracking/WV0ejI_zO3i1DGy0D1i00000Fuk74mK0Em8nd1x4OW00000uphyIO8mOQ0I00OIhcmM80SZsvG-G0UgqkStRW8200fW1whIvpLkm0QQTxgu8k06OeThg9DW1nh6Xfm7W0TpHXwS1c0AwjSCPe0Byr_4N-0IZ0eW5emAG1PC4e0LPg0LAi0LAk0M70S05-0p81QK3u0Lse0Rsqmoe1lRJ3Ca6Q6XANp8WVKUf1w3cR3LwT5Cqk0U01T0710RG29gAW872a846w0a7y0c07lW9y1202Wg02-YvGeWB3geB4EQTY7AWvW00-WeK30tZ1G21Y824X0Ie3w3Da-YZZzsfDBWF7e0Gw9Rv8v30WC88c16_X2MX4MVf4h3PP2cqXqMDW1IWW62e59C4ekwibGRO5S6AzkoZZxpyOu4Nc1VUeOulq1VGXWFO5vpoFO8O86KrCsCsDJ4rDcPZCpGrCZKuP3KuE68sCJWnOpTXD3Paq1W2-1Y06RWQ0e8S3KPjGZfMLZ9nMcnNOJUG7A0uc1p0km7f780TVw4TqBFCkGlMxJ-e7GAO7go44jWUiuqVe1_ZblaZi1y2o1_ZsD1Ju201q24E0BIMjKljIRCE9BjAGoVAPZE4fGJJipmlyyubL_RXKybyK8NbueozKL8PuXONCOW6~1?action-id=0 0xa5c9e4df NORMAL 11> [lifetime=9249], [size=0], [rc=200], [retryCount=0]
2022-07-05 14:21:12.614 25945-27816 D/Yandex Mobile Ads: [253205] bs0.a: HTTP response for request=<[ ] https://mobile.yandexadexchange.net/v4/ad 0x63e782f2 NORMAL 189> [lifetime=4638], [size=116052], [rc=200], [retryCount=0]
2022-07-05 14:21:15.006 25945-28094 E/Yandex Mobile Ads: [253270] ur0.a: Unhandled exception java.lang.RuntimeException: Bad URL 

java.lang.RuntimeException: Bad URL 
        at com.yandex.mobile.ads.impl.ab.a(SourceFile:125)
        at com.yandex.mobile.ads.impl.ur0.a(SourceFile:58)
        at com.yandex.mobile.ads.impl.ur0.run(SourceFile:4)
     Caused by: java.net.MalformedURLException: no protocol: 
        at java.net.URL.<init>(URL.java:601)
        at java.net.URL.<init>(URL.java:498)
        at java.net.URL.<init>(URL.java:447)
        at com.yandex.mobile.ads.impl.k90.a(SourceFile:13)
        at com.yandex.mobile.ads.impl.el0.a(SourceFile:13)
        at com.yandex.mobile.ads.impl.j90.a(SourceFile:7)
        at com.yandex.mobile.ads.impl.ab.a(SourceFile:10)
        at com.yandex.mobile.ads.impl.ur0.a(SourceFile:58) 
        at com.yandex.mobile.ads.impl.ur0.run(SourceFile:4) 
```

```
2022-07-05 14:40:17.454 31497-32349 D/Yandex Mobile Ads: [253645] bs0.a: HTTP response for request=<[ ] https://an.yandex.ru/tracking/WVCejI_zO3e1JGy0H1i000000KERIGK0EW8n5IF4OW00000uphyIO8mOQ0I00OIhcmM80SZsvG-G0UgqkStRW8200fW1whIvpLkm0QQTxgu8k06OeThg9DW1nh6Xfm7W0TpHXwS1c0AwjSCPe0Byr_4N-0JA0eW5oWAG1T82e0Lbg0LKi0LKk0LMm0Ny3CW5fWFW1NQW1lRJ3AW6zjCCoGPeQ4fVCY1zHwa7qy943uE5L3Iu1u05q0S41j08ceg0WSAGWGRe2GVm2O0U-0dm480A2e0BYezsY0iEgWiGzs9OEjF2002FGLPG3UC50868W8I41AWFquM3gh6meQeqk0yUW13eblaZaC20mWYO4R-49Q4HP-aIiDbaARI7HOs05A20OAWKqjWKekwibGRO5S6AzkoZZxpyOu4Nc1VUeOulq1VGXWFO5vpoFO8O86KrCsCsDJ4rDcPZCpGrCZKuP3KuE68sCJWnOpTXD3Paq1W2-1Y06RWQ0e8S3L9FEJepQpXCS6rNOJUG7A0uc1p0km7f780T_t-X7T2ppBaBrkq_g1q2c1wOjmlO7hED7w0VuvRv8x0V0iWVuzZGK-0W0T0X3m2jbhNBvdEp3YIxIaCdocOpv7RkPIcWXsXUvbrBhkoxfvBre0hBn1bx8wGonAmjOX0D~1?action-id=0 0xa5c9e4df NORMAL 1> [lifetime=9067], [size=0], [rc=200], [retryCount=0]
2022-07-05 14:40:17.781 31497-32349 E/Yandex Mobile Ads: [253645] ur0.a: Unhandled exception java.lang.RuntimeException: Bad URL 
    java.lang.RuntimeException: Bad URL 
        at com.yandex.mobile.ads.impl.ab.a(SourceFile:125)
        at com.yandex.mobile.ads.impl.ur0.a(SourceFile:58)
        at com.yandex.mobile.ads.impl.ur0.run(SourceFile:4)
     Caused by: java.net.MalformedURLException: no protocol: 
        at java.net.URL.<init>(URL.java:601)
        at java.net.URL.<init>(URL.java:498)
        at java.net.URL.<init>(URL.java:447)
        at com.yandex.mobile.ads.impl.k90.a(SourceFile:13)
        at com.yandex.mobile.ads.impl.el0.a(SourceFile:13)
        at com.yandex.mobile.ads.impl.j90.a(SourceFile:7)
        at com.yandex.mobile.ads.impl.ab.a(SourceFile:10)
        at com.yandex.mobile.ads.impl.ur0.a(SourceFile:58) 
        at com.yandex.mobile.ads.impl.ur0.run(SourceFile:4) 

```

**Comment by mobile-ads-github** [comment]
Добрый день, спасибо за обращение
Приложим усилия чтоб разобраться
Может быть у вас есть какая-нибудь дополнительная информация - с каким урлом возникает проблема?

**Comment by DimaKoz** [comment]
А в логах же урлы приведены:
[https://an.yandex.ru/tracking/WVCejI_zO3e1JGy0H1i000000KERIGK0EW8n5IF4OW00000uphyIO8mOQ0I00OIhcmM80SZsvG-G0UgqkStRW8200fW1whIvpLkm0QQTxgu8k06OeThg9DW1nh6Xfm7W0TpHXwS1c0AwjSCPe0Byr_4N-0JA0eW5oWAG1T82e0Lbg0LKi0LKk0LMm0Ny3CW5fWFW1NQW1lRJ3AW6zjCCoGPeQ4fVCY1zHwa7qy943uE5L3Iu1u05q0S41j08ceg0WSAGWGRe2GVm2O0U-0dm480A2e0BYezsY0iEgWiGzs9OEjF2002FGLPG3UC50868W8I41AWFquM3gh6meQeqk0yUW13eblaZaC20mWYO4R-49Q4HP-aIiDbaARI7HOs05A20OAWKqjWKekwibGRO5S6AzkoZZxpyOu4Nc1VUeOulq1VGXWFO5vpoFO8O86KrCsCsDJ4rDcPZCpGrCZKuP3KuE68sCJWnOpTXD3Paq1W2-1Y06RWQ0e8S3L9FEJepQpXCS6rNOJUG7A0uc1p0km7f780T_t-X7T2ppBaBrkq_g1q2c1wOjmlO7hED7w0VuvRv8x0V0iWVuzZGK-0W0T0X3m2jbhNBvdEp3YIxIaCdocOpv7RkPIcWXsXUvbrBhkoxfvBre0hBn1bx8wGonAmjOX0D~1?action-id=0](https://an.yandex.ru/tracking/WVCejI_zO3e1JGy0H1i000000KERIGK0EW8n5IF4OW00000uphyIO8mOQ0I00OIhcmM80SZsvG-G0UgqkStRW8200fW1whIvpLkm0QQTxgu8k06OeThg9DW1nh6Xfm7W0TpHXwS1c0AwjSCPe0Byr_4N-0JA0eW5oWAG1T82e0Lbg0LKi0LKk0LMm0Ny3CW5fWFW1NQW1lRJ3AW6zjCCoGPeQ4fVCY1zHwa7qy943uE5L3Iu1u05q0S41j08ceg0WSAGWGRe2GVm2O0U-0dm480A2e0BYezsY0iEgWiGzs9OEjF2002FGLPG3UC50868W8I41AWFquM3gh6meQeqk0yUW13eblaZaC20mWYO4R-49Q4HP-aIiDbaARI7HOs05A20OAWKqjWKekwibGRO5S6AzkoZZxpyOu4Nc1VUeOulq1VGXWFO5vpoFO8O86KrCsCsDJ4rDcPZCpGrCZKuP3KuE68sCJWnOpTXD3Paq1W2-1Y06RWQ0e8S3L9FEJepQpXCS6rNOJUG7A0uc1p0km7f780T_t-X7T2ppBaBrkq_g1q2c1wOjmlO7hED7w0VuvRv8x0V0iWVuzZGK-0W0T0X3m2jbhNBvdEp3YIxIaCdocOpv7RkPIcWXsXUvbrBhkoxfvBre0hBn1bx8wGonAmjOX0D~1?action-id=0)

**Comment by mobile-ads-github** [comment]
Добрый день, проблема должна быть исправлена в версии рекламного SDK 5.2.0.
Переоткройте пожалуйста issue, если получится воспроизвести проблему на версии 5.2.0.
