### ISSUE TITLE
ANR at com.yandex.mobile.ads.exo.h.j(h.java:8) 

### ISSUE THREAD

**Issue by DimaKoz** [yandexmobile/yandex-ads-sdk-android#151]
Используются версии библиотек:

```
com.yandex.android:mobileads:5.1.1
com.yandex.android:mobmetricalib:4.2.0
com.yandex.ads.mediation:mobileads-mytarget:5.15.0.0
com.my.target:mytarget-sdk:5.15.0
```

ANR:

```
main (waiting): tid=1 systid=21016 
       at java.lang.Object.wait(Object.java)
       at java.lang.Object.wait(Object.java:442)
       at java.lang.Object.wait(Object.java:568)
       at com.yandex.mobile.ads.exo.h.j(h.java:8)
       at com.yandex.mobile.ads.exo.g.o(g.java:5)
       at com.yandex.mobile.ads.exo.p.n(p.java:6)
       at com.yandex.mobile.ads.impl.t20.d(t20.java:8)
       at com.yandex.mobile.ads.impl.t20.a(t20.java:25)
       at com.yandex.mobile.ads.impl.uq0$b.a(uq0.java:4)
       at com.yandex.mobile.ads.impl.ff1.a(ff1.java:27)
       at com.yandex.mobile.ads.impl.t20$b.a(t20.java:15)
       at com.yandex.mobile.ads.impl.n20$b.a(n20.java:1)
       at com.yandex.mobile.ads.impl.gv0.c(gv0.java:10)
       at com.yandex.mobile.ads.impl.gv0.b(gv0.java:1)
       at com.yandex.mobile.ads.impl.gv0$b.run(gv0.java:2)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:8069)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
```
<img width="434" alt="Screenshot 2022-07-26 at 15 13 40" src="https://user-images.githubusercontent.com/3092276/181003314-9eccac3a-2881-4321-b375-e2f696eef987.png">

**Comment by mobile-ads-github** [comment]
Здравствуйте, спасибо за обращение, мы взяли задачу в работу.

Пока можем порекомендовать обновить версию Ads SDK до 5.2.0 и AppMetrica до 5.0.0. 
```
com.yandex.android:mobileads:5.2.0
com.yandex.android:mobmetricalib:5.0.0
com.yandex.ads.mediation:mobileads-mytarget:5.15.0.1
com.my.target:mytarget-sdk:5.15.0
```

**Comment by mobile-ads-github** [comment]
Добрый день, проблема исправлена в версии SDK 5.4.0.
