### ISSUE TITLE
Fatal Exception: java.lang.StackOverflowError stack size 8192KB

### ISSUE THREAD

**Issue by DjentAgent** [yandexmobile/yandex-ads-sdk-android#157]
Получаем многочисленные краши (уже более ста) со следующим стектрейсом : 

Fatal Exception: java.lang.StackOverflowError: stack size 8192KB
       at java.nio.charset.CharsetDecoder.<init>(CharsetDecoder.java:199)
       at java.nio.charset.CharsetDecoder.<init>(CharsetDecoder.java:235)
       at com.android.icu.charset.CharsetDecoderICU.<init>(CharsetDecoderICU.java:77)
       at com.android.icu.charset.CharsetDecoderICU.newInstance(CharsetDecoderICU.java:63)
       at com.android.icu.charset.CharsetICU.newDecoder(CharsetICU.java:42)
       at android.net.UriCodec.appendDecoded(UriCodec.java:94)
       at android.net.UriCodec.decode(UriCodec.java:79)
       at android.net.Uri.decode(Uri.java:1977)
       at android.net.Uri$AbstractHierarchicalUri.parseHost(Uri.java:1127)
       at android.net.Uri$AbstractHierarchicalUri.getHost(Uri.java:1110)
       at com.yandex.mobile.ads.impl.l41.b(SourceFile:5)
       at com.yandex.mobile.ads.impl.l41.<init>(SourceFile:93)
       at com.yandex.mobile.ads.impl.tb.<init>(SourceFile:1)
       at com.yandex.mobile.ads.impl.iz0.<init>(SourceFile:1)
       at com.yandex.mobile.ads.impl.km1.a(SourceFile:42)
       at com.yandex.mobile.ads.impl.in1.a(SourceFile:42)
       at com.yandex.mobile.ads.impl.in1.a(SourceFile:13)
       at com.yandex.mobile.ads.impl.ml1.a(SourceFile:43)
       at com.yandex.mobile.ads.impl.ah.a(SourceFile:363)
       at com.yandex.mobile.ads.impl.ln1.a(SourceFile:6)
       at com.yandex.mobile.ads.impl.lk1.a(SourceFile:25)
       at com.yandex.mobile.ads.impl.w40.a(SourceFile:24)
       at com.yandex.mobile.ads.impl.du0$b.a(SourceFile:4)
       at com.yandex.mobile.ads.impl.lk1.a(SourceFile:27)
       at com.yandex.mobile.ads.impl.w40.a(SourceFile:24)
       at com.yandex.mobile.ads.impl.du0$b.a(SourceFile:4)
       at com.yandex.mobile.ads.impl.lk1.a(SourceFile:27)
       at com.yandex.mobile.ads.impl.w40.a(SourceFile:24)
       at com.yandex.mobile.ads.impl.du0$b.a(SourceFile:4)
       at com.yandex.mobile.ads.impl.lk1.a(SourceFile:27)
       at com.yandex.mobile.ads.impl.w40.a(SourceFile:24)
       at com.yandex.mobile.ads.impl.du0$b.a(SourceFile:4)
       at com.yandex.mobile.ads.impl.lk1.a(SourceFile:27)
       at com.yandex.mobile.ads.impl.w40.a(SourceFile:24)
       at com.yandex.mobile.ads.impl.du0$b.a(SourceFile:4)
       at com.yandex.mobile.ads.impl.lk1.a(SourceFile:27)
       at com.yandex.mobile.ads.impl.w40.a(SourceFile:24)
       at com.yandex.mobile.ads.impl.du0$b.a(SourceFile:4)
       at com.yandex.mobile.ads.impl.lk1.a(SourceFile:27)
       at com.yandex.mobile.ads.impl.w40.a(SourceFile:24)
       at com.yandex.mobile.ads.impl.du0$b.a(SourceFile:4)
       at com.yandex.mobile.ads.impl.lk1.a(SourceFile:27)
       at com.yandex.mobile.ads.impl.w40.a(SourceFile:24)
       at com.yandex.mobile.ads.impl.du0$b.a(SourceFile:4)
       at com.yandex.mobile.ads.impl.lk1.a(SourceFile:27)
       at com.yandex.mobile.ads.impl.w40.a(SourceFile:24)
       at com.yandex.mobile.ads.impl.du0$b.a(SourceFile:4)
       at com.yandex.mobile.ads.impl.lk1.a(SourceFile:27)
       at com.yandex.mobile.ads.impl.w40.a(SourceFile:24)
       at com.yandex.mobile.ads.impl.du0$b.a(SourceFile:4)
       at com.yandex.mobile.ads.impl.lk1.a(SourceFile:27)
       at com.yandex.mobile.ads.impl.w40$b.a(SourceFile:15)
       at com.yandex.mobile.ads.impl.q40$b.a(SourceFile:1)
       at com.yandex.mobile.ads.impl.wy0.c(SourceFile:10)
       at com.yandex.mobile.ads.impl.wy0.b(SourceFile:1)
       at com.yandex.mobile.ads.impl.wy0$b.run(SourceFile:2)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7948)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:603)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
       
       
       Fatal Exception: java.lang.StackOverflowError: stack size 8MB
       at com.yandex.mobile.ads.impl.iz0.a(SourceFile:1)
       at com.yandex.mobile.ads.impl.iz0.<init>(SourceFile:3)
       at com.yandex.mobile.ads.impl.km1.a(SourceFile:42)
       at com.yandex.mobile.ads.impl.in1.a(SourceFile:42)
       at com.yandex.mobile.ads.impl.in1.a(SourceFile:13)
       at com.yandex.mobile.ads.impl.ml1.a(SourceFile:43)
       at com.yandex.mobile.ads.impl.ah.a(SourceFile:363)
       at com.yandex.mobile.ads.impl.ln1.a(SourceFile:6)
       at com.yandex.mobile.ads.impl.lk1.a(SourceFile:25)
       at com.yandex.mobile.ads.impl.w40.a(SourceFile:24)
       at com.yandex.mobile.ads.impl.du0$b.a(SourceFile:4)
       at com.yandex.mobile.ads.impl.lk1.a(SourceFile:27)
       at com.yandex.mobile.ads.impl.w40.a(SourceFile:24)
       at com.yandex.mobile.ads.impl.du0$b.a(SourceFile:4)
       at com.yandex.mobile.ads.impl.lk1.a(SourceFile:27)
       at com.yandex.mobile.ads.impl.w40.a(SourceFile:24)
       at com.yandex.mobile.ads.impl.du0$b.a(SourceFile:4)
       at com.yandex.mobile.ads.impl.lk1.a(SourceFile:27)
       at com.yandex.mobile.ads.impl.w40.a(SourceFile:24)
       at com.yandex.mobile.ads.impl.du0$b.a(SourceFile:4)
       at com.yandex.mobile.ads.impl.lk1.a(SourceFile:27)
       at com.yandex.mobile.ads.impl.w40.a(SourceFile:24)
       at com.yandex.mobile.ads.impl.du0$b.a(SourceFile:4)
       at com.yandex.mobile.ads.impl.lk1.a(SourceFile:27)
       at com.yandex.mobile.ads.impl.w40.a(SourceFile:24)
       at com.yandex.mobile.ads.impl.du0$b.a(SourceFile:4)
       at com.yandex.mobile.ads.impl.lk1.a(SourceFile:27)
       at com.yandex.mobile.ads.impl.w40.a(SourceFile:24)
       at com.yandex.mobile.ads.impl.du0$b.a(SourceFile:4)
       at com.yandex.mobile.ads.impl.lk1.a(SourceFile:27)
       at com.yandex.mobile.ads.impl.w40.a(SourceFile:24)
       at com.yandex.mobile.ads.impl.du0$b.a(SourceFile:4)
       at com.yandex.mobile.ads.impl.lk1.a(SourceFile:27)
       at com.yandex.mobile.ads.impl.w40.a(SourceFile:24)
       at com.yandex.mobile.ads.impl.du0$b.a(SourceFile:4)
       at com.yandex.mobile.ads.impl.lk1.a(SourceFile:27)
       at com.yandex.mobile.ads.impl.w40.a(SourceFile:24)
       at com.yandex.mobile.ads.impl.du0$b.a(SourceFile:4)
       at com.yandex.mobile.ads.impl.lk1.a(SourceFile:27)
       at com.yandex.mobile.ads.impl.w40$b.a(SourceFile:15)
       at com.yandex.mobile.ads.impl.q40$b.a(SourceFile:1)
       at com.yandex.mobile.ads.impl.wy0.c(SourceFile:10)
       at com.yandex.mobile.ads.impl.wy0.b(SourceFile:1)
       at com.yandex.mobile.ads.impl.wy0$b.run(SourceFile:2)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6719)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:449)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
       
Версии андроид и вендоры смартфонов:       

![image](https://user-images.githubusercontent.com/20524738/188598036-a842ec85-a9f6-4f26-b31b-9e421736647e.png)
![image](https://user-images.githubusercontent.com/20524738/188598088-d1c795a1-24ec-4f5a-910c-53a43d0ff96b.png)

**Comment by DjentAgent** [comment]
Версия сдк 5.2.1

**Comment by mobile-ads-github** [comment]
Здравствуйте, спасибо что сообщили о проблеме, будем разбираться

**Comment by mobile-ads-github** [comment]
Добрый день! Фикс вашей проблемы был добавлен в 5.3.0, советуем обновиться

**Comment by DjentAgent** [comment]
> Добрый день! Фикс вашей проблемы был добавлен в 5.3.0, советуем обновиться

Спасибо! Попробуем в ближайшее время!
