### ISSUE TITLE
StackOverflowError at l41 line 5

### ISSUE THREAD

**Issue by Jovandine** [yandexmobile/yandex-ads-sdk-android#162]
Hello
Yandex ads version 5.3.0

![Снимок экрана 2022-10-03 в 13 54 27](https://user-images.githubusercontent.com/8447884/193527288-0583f3b8-9d67-49ff-832e-9469b372c20b.png)

Fatal Exception: java.lang.StackOverflowError: stack size 8192KB
       at java.util.concurrent.atomic.AtomicInteger.addAndGet(AtomicInteger.java:206)
       at dalvik.system.VMRuntime.notifyNativeAllocation(VMRuntime.java:570)
       at libcore.util.NativeAllocationRegistry.registerNativeAllocation(NativeAllocationRegistry.java:299)
       at libcore.util.NativeAllocationRegistry.registerNativeAllocation(NativeAllocationRegistry.java:247)
       at com.android.icu.charset.NativeConverter.registerConverter(NativeConverter.java:34)
       at com.android.icu.charset.CharsetDecoderICU.newInstance(CharsetDecoderICU.java:71)
       at com.android.icu.charset.CharsetICU.newDecoder(CharsetICU.java:42)
       at android.net.UriCodec.appendDecoded(UriCodec.java:94)
       at android.net.UriCodec.decode(UriCodec.java:79)
       at android.net.Uri.decode(Uri.java:1977)
       at android.net.Uri$AbstractHierarchicalUri.parseHost(Uri.java:1127)
       at android.net.Uri$AbstractHierarchicalUri.getHost(Uri.java:1110)
       at com.yandex.mobile.ads.impl.l41.b(SourceFile:5)
       at com.yandex.mobile.ads.impl.l41.<init>(SourceFile:93)
       at com.yandex.mobile.ads.impl.tb.<init>(SourceFile:1)
       at com.yandex.mobile.ads.impl.iz0.<init>(SourceFile:1)
       at com.yandex.mobile.ads.impl.km1.a(SourceFile:42)
       at com.yandex.mobile.ads.impl.in1.a(SourceFile:42)
       at com.yandex.mobile.ads.impl.in1.a(SourceFile:13)
       at com.yandex.mobile.ads.impl.ml1.a(SourceFile:43)
       at com.yandex.mobile.ads.impl.ah.a(SourceFile:363)
       at com.yandex.mobile.ads.impl.ln1.a(SourceFile:6)
       at com.yandex.mobile.ads.impl.lk1.a(SourceFile:25)
       at com.yandex.mobile.ads.impl.w40.a(SourceFile:24)
       at com.yandex.mobile.ads.impl.du0$b.a(SourceFile:4)
       at com.yandex.mobile.ads.impl.lk1.a(SourceFile:27)
       at com.yandex.mobile.ads.impl.w40.a(SourceFile:24)
       at com.yandex.mobile.ads.impl.du0$b.a(SourceFile:4)
       at com.yandex.mobile.ads.impl.lk1.a(SourceFile:27)
       at com.yandex.mobile.ads.impl.w40.a(SourceFile:24)
       at com.yandex.mobile.ads.impl.du0$b.a(SourceFile:4)
       at com.yandex.mobile.ads.impl.lk1.a(SourceFile:27)
       at com.yandex.mobile.ads.impl.w40.a(SourceFile:24)
       at com.yandex.mobile.ads.impl.du0$b.a(SourceFile:4)
       at com.yandex.mobile.ads.impl.lk1.a(SourceFile:27)
       at com.yandex.mobile.ads.impl.w40.a(SourceFile:24)
       at com.yandex.mobile.ads.impl.du0$b.a(SourceFile:4)
       at com.yandex.mobile.ads.impl.lk1.a(SourceFile:27)
       at com.yandex.mobile.ads.impl.w40.a(SourceFile:24)
       at com.yandex.mobile.ads.impl.du0$b.a(SourceFile:4)
       at com.yandex.mobile.ads.impl.lk1.a(SourceFile:27)
       at com.yandex.mobile.ads.impl.w40.a(SourceFile:24)
       at com.yandex.mobile.ads.impl.du0$b.a(SourceFile:4)
       at com.yandex.mobile.ads.impl.lk1.a(SourceFile:27)
       at com.yandex.mobile.ads.impl.w40.a(SourceFile:24)
       at com.yandex.mobile.ads.impl.du0$b.a(SourceFile:4)
       at com.yandex.mobile.ads.impl.lk1.a(SourceFile:27)
       at com.yandex.mobile.ads.impl.w40.a(SourceFile:24)
       at com.yandex.mobile.ads.impl.du0$b.a(SourceFile:4)
       at com.yandex.mobile.ads.impl.lk1.a(SourceFile:27)
       at com.yandex.mobile.ads.impl.w40.a(SourceFile:24)
       at com.yandex.mobile.ads.impl.du0$b.a(SourceFile:4)
       at com.yandex.mobile.ads.impl.lk1.a(SourceFile:27)
       at com.yandex.mobile.ads.impl.w40$b.a(SourceFile:15)
       at com.yandex.mobile.ads.impl.q40$b.a(SourceFile:1)
       at com.yandex.mobile.ads.impl.wy0.c(SourceFile:10)
       at com.yandex.mobile.ads.impl.wy0.b(SourceFile:1)
       at com.yandex.mobile.ads.impl.wy0$b.run(SourceFile:2)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:7876)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

**Comment by mobile-ads-github** [comment]
Hello. Based on Ad SDK analytics, your app with build number 489 uses Ad SDK 5.2.1. Did the same crash occur in your latest app build - 491? Your latest app with build number 491 uses Ad SDK 5.3.0 with a fixed crash.

**Comment by Jovandine** [comment]
Sorry, my mistake. This error was fixed with version 5.3.0
