### ISSUE TITLE
5.3.0  [md line 45] UnsupportedOperationException: Empty collection can't be reduced

### ISSUE THREAD

**Issue by Jovandine** [yandexmobile/yandex-ads-sdk-android#169]
Добрый день.
Появился такой краш в версии 5.3.0

Fatal Exception: java.lang.UnsupportedOperationException: Empty collection can't be reduced.
       at com.yandex.mobile.ads.impl.md.a(SourceFile:45)
       at com.yandex.mobile.ads.impl.ij1.a(SourceFile:35)
       at com.yandex.mobile.ads.impl.ij1.$r8$lambda$hQHPW5k4VPa2-aKyEMit1m9jFbs()
       at com.yandex.mobile.ads.impl.ij1$$ExternalSyntheticLambda0.run(:6)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8855)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

![Снимок экрана 2022-10-17 в 11 33 37](https://user-images.githubusercontent.com/8447884/196096986-bcfbc962-3904-441a-9c0f-5d9168ea41fc.png)

**Comment by mobile-ads-github** [comment]
Здравствуйте, спасибо что сообщили о проблеме, исправим в ближайшее время

**Comment by mobile-ads-github** [comment]
Сегодня реши должны были полностью пропасть
