### ISSUE TITLE
Deadlock at com.yandex.mobile.ads.banner.g.destroy (g.java:2) (com.yandex.android:mobileads:5.3.2)

### ISSUE THREAD

**Issue by DimaKoz** [yandexmobile/yandex-ads-sdk-android#175]
`com.yandex.android:mobmetricalib:5.2.0`
`com.yandex.android:mobileads:5.3.2`

```
main (blocked):tid=1 systid=16429 | waiting to lock <0x073373ad> (java.lang.Object) held by thread 36
       at com.yandex.mobile.ads.impl.l9.a(l9.java:8)
       at com.yandex.mobile.ads.impl.ub.a(ub.java:12)
       at com.yandex.mobile.ads.impl.oc.c(oc.java:25)
       at com.yandex.mobile.ads.impl.mg0.c(mg0.java:1)
       at com.yandex.mobile.ads.impl.ap1.c(ap1.java:3)
       at com.yandex.mobile.ads.banner.k.c(k.java:1)
       at com.yandex.mobile.ads.banner.b.c(b.java:27)
       at com.yandex.mobile.ads.banner.b.A(b.java:2)
       at com.yandex.mobile.ads.banner.g.destroy(g.java:2)
       at com.yandex.mobile.ads.banner.BannerAdView.destroy(BannerAdView.java:1)
```
       
       
 ```
  YMM-APT-1 (blocked):tid=36 systid=16481 | waiting to lock <0x0401e2ec> (com.yandex.mobile.ads.banner.b) held by thread 1
       at com.yandex.mobile.ads.impl.oc.c(oc.java:18)
       at com.yandex.mobile.ads.impl.oc$b$a.a(oc.java:3)
       at com.yandex.mobile.ads.impl.l9.a(l9.java:15)
       at com.yandex.mobile.ads.impl.l9.b(l9.java:1)
       at com.yandex.mobile.ads.impl.j9$b.onResult(j9.java:4)
       at com.yandex.metrica.impl.ob.Gf$e$a.onResult(Gf.java:1)
       at com.yandex.metrica.impl.ob.Tj.a(Tj.java:51)
       at com.yandex.metrica.impl.ob.ol.a(ol.java:446)
       at com.yandex.metrica.impl.ob.nl.run(nl.java:47)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:268)
       at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by mobile-ads-github** [comment]
Добрый день, спасибо за репорт! Исправим в следующем релизе рекламного SDK.

**Comment by DimaKoz** [comment]
Не очень часто, редкая проблема, хотя она есть и сама не пропадёт. 
Добавил ещё информацию:

<img width="438" alt="1" src="https://user-images.githubusercontent.com/3092276/208423344-8ce7ee5b-55d9-441c-8b5b-3e5f95ad1d07.png">
<img width="425" alt="2" src="https://user-images.githubusercontent.com/3092276/208423349-536e3088-fcd3-41e4-8903-08325bd23109.png">
<img width="430" alt="3" src="https://user-images.githubusercontent.com/3092276/208423354-5c5952f2-84df-4d97-9822-98d095e5b33c.png">

**Comment by mobile-ads-github** [comment]
Добрый день, выпустили релиз 5.5.0 с исправлением данной проблемы.
