### ISSUE TITLE
SQLiteDatabaseLockedException at at com.yandex.mobile.ads.impl.zg$a.a(zg.java:5)

### ISSUE THREAD

**Issue by DimaKoz** [yandexmobile/yandex-ads-sdk-android#176]
```
mobileads:5.4.1
mobmetricalib:5.2.0
```

```
Fatal Exception: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (Sqlite code 5 SQLITE_BUSY), (OS error - 0:Success)
       at android.database.sqlite.SQLiteConnection.nativeExecuteForLong(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.executeForLong(SQLiteConnection.java:737)
       at android.database.sqlite.SQLiteSession.executeForLong(SQLiteSession.java:674)
       at android.database.sqlite.SQLiteStatement.simpleQueryForLong(SQLiteStatement.java:109)
       at android.database.DatabaseUtils.longForQuery(DatabaseUtils.java:935)
       at android.database.DatabaseUtils.longForQuery(DatabaseUtils.java:923)
       at android.database.sqlite.SQLiteDatabase.getVersion(SQLiteDatabase.java:1026)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:409)
       at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:356)
       at com.yandex.mobile.ads.impl.zg$a.a(zg.java:5)
       at com.yandex.mobile.ads.impl.zg.a(zg.java:5)
       at com.yandex.mobile.ads.impl.yn1.a(yn1.java:107)
       at com.yandex.mobile.ads.impl.yn1$a.run(yn1.java:3)
```

**Comment by mobile-ads-github** [comment]
Добрый день. Спасибо за репорт, мы выпустим версию SDK с исправлением в начале следующей недели.

**Comment by mobile-ads-github** [comment]
Добрый день, выпустили релиз 5.5.0 с исправлением данной проблемы.
