### ISSUE TITLE
AndroidRuntimeException at com.yandex.mobile.ads.impl.zd.<init>(zd.java:1) (No WebView installed)

### ISSUE THREAD

**Issue by DimaKoz** [yandexmobile/yandex-ads-sdk-android#177]
```
mobileads:5.4.1
mobmetricalib:5.2.0
```

```
android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
       at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:423)
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:194)
       at android.webkit.WebView.getFactory(WebView.java:2536)
       at android.webkit.WebView.ensureProviderCreated(WebView.java:2531)
       at android.webkit.WebView.setOverScrollMode(WebView.java:2596)
       at android.view.View.<init>(View.java:4588)
       at android.view.View.<init>(View.java:4722)
       at android.view.ViewGroup.<init>(ViewGroup.java:597)
       at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
       at android.webkit.WebView.<init>(WebView.java:643)
       at android.webkit.WebView.<init>(WebView.java:588)
       at android.webkit.WebView.<init>(WebView.java:571)
       at android.webkit.WebView.<init>(WebView.java:558)
       at android.webkit.WebView.<init>(WebView.java:548)
       at com.yandex.mobile.ads.impl.zd.<init>(zd.java:1)
       at com.yandex.mobile.ads.impl.ta1.<init>(ta1.java:1)
       at com.yandex.mobile.ads.impl.d11.<init>(d11.java:1)
       at com.yandex.mobile.ads.impl.i11.a(i11.java:2)
       at com.yandex.mobile.ads.impl.yx0.a(yx0.java:3)
       at com.yandex.mobile.ads.impl.wa2.a(wa2.java:12)
       at com.yandex.mobile.ads.impl.vx0.a(vx0.java:2)
       at com.yandex.mobile.ads.impl.ra.a(ra.java:5)
       at com.yandex.mobile.ads.impl.sa.a(sa.java:39)
       at com.yandex.mobile.ads.nativeads.w.<init>(w.java:13)
       at com.yandex.mobile.ads.nativeads.l0.a(l0.java:14)
       at com.yandex.mobile.ads.nativeads.m.bindNativeAd(m.java:6)
       ...
       at AdsHolder$onBind$listener$1.onAdLoaded(AdsHolder.java:148)
       at com.yandex.mobile.ads.nativeads.t.a(t.java:14)
       at com.yandex.mobile.ads.nativeads.t.$r8$lambda$YhpTySBNlf8AQXfqKYJX-vKgziI(t.java)
       at com.yandex.mobile.ads.nativeads.t$$InternalSyntheticLambda$1$feb029488fb8729bbffd70d6792eea31d2545a23c59f7042ba7d856a1e659527$0.run(t.java:4)
       at android.os.Handler.handleCallback(Handler.java:794)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:173)
       at android.app.ActivityThread.main(ActivityThread.java:6651)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:822)
```

```
Caused by android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
       at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:319)
       at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:383)
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:194)
       at android.webkit.WebView.getFactory(WebView.java:2536)
       at android.webkit.WebView.ensureProviderCreated(WebView.java:2531)
       at android.webkit.WebView.setOverScrollMode(WebView.java:2596)
       at android.view.View.<init>(View.java:4588)
       at android.view.View.<init>(View.java:4722)
       at android.view.ViewGroup.<init>(ViewGroup.java:597)
       at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
       at android.webkit.WebView.<init>(WebView.java:643)
       at android.webkit.WebView.<init>(WebView.java:588)
       at android.webkit.WebView.<init>(WebView.java:571)
       at android.webkit.WebView.<init>(WebView.java:558)
       at android.webkit.WebView.<init>(WebView.java:548)
       at com.yandex.mobile.ads.impl.zd.<init>(zd.java:1)
       at com.yandex.mobile.ads.impl.ta1.<init>(ta1.java:1)
       at com.yandex.mobile.ads.impl.d11.<init>(d11.java:1)
       at com.yandex.mobile.ads.impl.i11.a(i11.java:2)
       at com.yandex.mobile.ads.impl.yx0.a(yx0.java:3)
       at com.yandex.mobile.ads.impl.wa2.a(wa2.java:12)
       at com.yandex.mobile.ads.impl.vx0.a(vx0.java:2)
       at com.yandex.mobile.ads.impl.ra.a(ra.java:5)
       at com.yandex.mobile.ads.impl.sa.a(sa.java:39)
       at com.yandex.mobile.ads.nativeads.w.<init>(w.java:13)
       at com.yandex.mobile.ads.nativeads.l0.a(l0.java:14)
       at com.yandex.mobile.ads.nativeads.m.bindNativeAd(m.java:6)
```

**Comment by mobile-ads-github** [comment]
Здравствуйте, спасибо, что сообщили о проблеме. Возьмем в работу.

**Comment by mobile-ads-github** [comment]
Добрый день, исправили проблему в релизе 5.5.1.
