### ISSUE TITLE
ANR at com.yandex.mobile.ads.impl.ec1.a(ec1.java:26) (mobileads:5.4.1)

### ISSUE THREAD

**Issue by DimaKoz** [yandexmobile/yandex-ads-sdk-android#178]
```
mobileads:5.4.1
mobmetricalib:5.2.0
```

```
main (native):tid=1 systid=30795 
#00 pc 0x75f30 libc.so (syscall + 32)
#01 pc 0x47cc80 libart.so (art::ConditionVariable::WaitHoldingLocks(art::Thread*) + 140)
#02 pc 0x75bbf8 libart.so (artJniMethodEnd + 204)
#03 pc 0x20facc libart.so (art_jni_method_end + 12)
       at android.os.BinderProxy.transactNative(BinderProxy.java)
       at android.os.BinderProxy.transact(BinderProxy.java:635)
       at android.view.IWindowManager$Stub$Proxy.isKeyguardLocked(IWindowManager.java:3604)
       at android.app.KeyguardManager.isKeyguardLocked(KeyguardManager.java:496)
       at com.yandex.mobile.ads.impl.ec1.a(ec1.java:26)
       at com.yandex.mobile.ads.impl.ec1.b(ec1.java:16)
       at com.yandex.mobile.ads.nativeads.v.a(v.java:3)
       at com.yandex.mobile.ads.nativeads.l0$b.b(l0.java:1)
       at com.yandex.mobile.ads.impl.l11.a(l11.java:27)
       at com.yandex.mobile.ads.impl.l11$b.handleMessage(l11.java:10)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:233)
       at android.os.Looper.loop(Looper.java:344)
       at android.app.ActivityThread.main(ActivityThread.java:8212)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
```

**Comment by mobile-ads-github** [comment]
Здравствуйте, спасибо, что сообщили о проблеме. Возьмем в работу.

**Comment by mobile-ads-github** [comment]
Можете подсказать, как часто проблема встречается и на каких устройствах?

**Comment by mobile-ads-github** [comment]
Судя по stacktrace проблема возникает в системном вызове, вероятнее всего происходит лаг в самой системе.
Если проблема воспроизводится часто переоткройте issue, пожалуйста.
