### ISSUE TITLE
ANR at com.yandex.mobile.ads.impl.ec1.a(ec1.java:24) (mobileads:5.4.1)

### ISSUE THREAD

**Issue by DimaKoz** [yandexmobile/yandex-ads-sdk-android#179]
```
mobileads:5.4.1
mobmetricalib:5.2.0
```

```
main (runnable):tid=1 systid=2836 
       at android.content.ContextWrapper.getSystemService(ContextWrapper.java:869)
       at com.yandex.mobile.ads.impl.ec1.a(ec1.java:24)
       at com.yandex.mobile.ads.impl.ec1.b(ec1.java:16)
       at com.yandex.mobile.ads.nativeads.v.a(v.java:3)
       at com.yandex.mobile.ads.nativeads.l0$b.b(l0.java:1)
       at com.yandex.mobile.ads.impl.l11.a(l11.java:27)
       at com.yandex.mobile.ads.impl.l11$b.handleMessage(l11.java:10)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:233)
       at android.os.Looper.loop(Looper.java:344)
       at android.app.ActivityThread.main(ActivityThread.java:8212)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
```

**Comment by mobile-ads-github** [comment]
Здравствуйте, спасибо, что сообщили о проблеме. Возьмем в работу.

**Comment by mobile-ads-github** [comment]
Судя по stacktrace проблема возникает в системном вызове, вероятнее всего происходит лаг в самой системе.
Если проблема воспроизводится часто переоткройте issue, пожалуйста.
