### ISSUE TITLE
ConcurrentModificationException at com.yandex.mobile.ads.nativeads.p$1.a(SourceFile:1091)

### ISSUE THREAD

**Issue by Lex1717** [yandexmobile/yandex-ads-sdk-android#18]
Версии: mobileads:2.61
               mobmetricalib:2.77

Стало часто падать приложение: #0. Crashed: main: 0 0 0x0000000000000000
       at java.util.HashMap$HashIterator.nextEntry(HashMap.java:787)
       at java.util.HashMap$KeyIterator.next(HashMap.java:814)
       at com.yandex.mobile.ads.nativeads.p$1.a(SourceFile:1091)
       at com.yandex.mobile.ads.ac$1$1.a(SourceFile:95)
       at com.yandex.mobile.ads.ac$1$1.a(SourceFile:88)
       at com.yandex.mobile.ads.g.a.b.g$3.run(SourceFile:477)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:168)
       at android.app.ActivityThread.main(ActivityThread.java:5885)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)

Полные логи можно посмотреть в приложенном файле.
Версии ОС: от 4 до 7, устройства разных брендов.
[crash_logs.txt](https://github.com/yandexmobile/yandex-ads-sdk-android/files/1436465/crash_logs.txt)

Как поступить с этой проблемой? Спасибо за помощь!

**Comment by satsakul** [comment]
Добрый день. 
Спасибо за предоставленную информацию.

Как часто возникает проблема? Данная ошибка появляется при ручной или автоматической загрузке картинок?

**Comment by Lex1717** [comment]
Проблема возникает около 20 раз на тысячу сессий. Загрузка картинок автоматическая.

**Comment by satsakul** [comment]
Спасибо. 
Мы создали задачу на исследование и решение данной проблемы. Постараемся решить её в ближайших релизах.

**Comment by Lex1717** [comment]
@satsakul, Добрый день.
До обновления нашего приложения стояли следующие версии библиотек:
mobileads:2.51, mobmetricalib:2.62. Проблем с ними не было.
С учетом того, что количество пользователей с падениями растет, думаем откатиться назад.
С учетом того, что версии библиотек старые, как по Вашему, лучше дождаться релиза или все же откатиться к вышеупомянутым версиям библиотек?

**Comment by satsakul** [comment]
Добрый день. Правка не будет включена в ближайший релиз, который находится уже на стадии тестирования. Поэтому быть может есть смысл в откате рекламной SDK до версии 2.51.

**Comment by yvasileuski** [comment]
Что касается mobmetricalib, то ее нельзя откатывать, так как она использует sql бд и не поддерживает downgrade.

**Comment by satsakul** [comment]
Добрый день.
Проблема будет исправлена в версии 2.70

**Comment by satsakul** [comment]
Добрый день. Вышел релиз версии 2.70, в которой проблема была устранена. Спасибо
