### ISSUE TITLE
Fatal Exception: android.database.sqlite.SQLiteDatabaseLockedException (5.4.1)

### ISSUE THREAD

**Issue by DjentAgent** [yandexmobile/yandex-ads-sdk-android#181]
В sdk (com.yandex.android:mobileads) версии 5.4.1 новый краш : 

Fatal Exception: android.database.sqlite.SQLiteDatabaseLockedException
database is locked (Sqlite code 5), (OS error - 2:No such file or directory)

Fatal Exception: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (Sqlite code 5), (OS error - 2:No such file or directory)
       at android.database.sqlite.SQLiteConnection.nativeExecuteForLong(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.executeForLong(SQLiteConnection.java:615)
       at android.database.sqlite.SQLiteSession.executeForLong(SQLiteSession.java:652)
       at android.database.sqlite.SQLiteStatement.simpleQueryForLong(SQLiteStatement.java:107)
       at android.database.DatabaseUtils.longForQuery(DatabaseUtils.java:886)
       at android.database.DatabaseUtils.longForQuery(DatabaseUtils.java:874)
       at android.database.sqlite.SQLiteDatabase.getVersion(SQLiteDatabase.java:916)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:257)
       at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:199)
       at com.yandex.mobile.ads.impl.zg$a.a(SourceFile:5)
       at com.yandex.mobile.ads.impl.zg.a(SourceFile:5)
       at com.yandex.mobile.ads.impl.yn1.a(SourceFile:107)
       at com.yandex.mobile.ads.impl.yn1$a.run(SourceFile:3)

![image](https://user-images.githubusercontent.com/20524738/211532034-51d35cec-1178-48f9-a4db-1591c0f30bee.png)

**Comment by mobile-ads-github** [comment]
Добрый день. Данная проблема была исправлена в версии рекламного SDK 5.5.0. Обновление версии SDK должно помочь.
