### ISSUE TITLE
Не понятно что за крэши

### ISSUE THREAD

**Issue by NikiHard** [yandexmobile/yandex-ads-sdk-android#189]
java.util.IllformedLocaleException: Ill-formed region: RID [at index 0]
	at java.util.Locale$Builder.setLocale(Locale.java:2877)
	at org.chromium.base.LocaleUtils.getDefaultLocaleListString(chromium-TrichromeWebViewGoogle.aab-beta-556301543:41)
	at org.chromium.android_webview.AwContents.G(chromium-TrichromeWebViewGoogle.aab-beta-556301543:1)
	at org.chromium.android_webview.AwContents.<init>(chromium-TrichromeWebViewGoogle.aab-beta-556301543:95)
	at com.android.webview.chromium.k.run(chromium-TrichromeWebViewGoogle.aab-beta-556301543:111)
	at Yz0.b(chromium-TrichromeWebViewGoogle.aab-beta-556301543:20)
	at Xz0.run(chromium-TrichromeWebViewGoogle.aab-beta-556301543:3)
	at org.chromium.base.task.PostTask.c(chromium-TrichromeWebViewGoogle.aab-beta-556301543:17)
	at Yz0.a(chromium-TrichromeWebViewGoogle.aab-beta-556301543:29)
	at com.android.webview.chromium.WebViewChromiumFactoryProvider.a(chromium-TrichromeWebViewGoogle.aab-beta-556301543:3)
	at com.android.webview.chromium.WebViewChromium.init(chromium-TrichromeWebViewGoogle.aab-beta-556301543:327)
	at android.webkit.WebView.<init>(WebView.java:448)
	at android.webkit.WebView.<init>(WebView.java:368)
	at android.webkit.WebView.<init>(WebView.java:350)
	at android.webkit.WebView.<init>(WebView.java:337)
	at android.webkit.WebView.<init>(WebView.java:327)
	at com.yandex.mobile.ads.impl.zd.<init>(SourceFile:1)
	at com.yandex.mobile.ads.impl.ta1.<init>(SourceFile:5)
	at com.yandex.mobile.ads.impl.kj0.<init>(SourceFile:1)
	at com.yandex.mobile.ads.banner.e.<init>(SourceFile:1)
	at com.yandex.mobile.ads.banner.b.a(SourceFile:63)
	at com.yandex.mobile.ads.banner.b.a(SourceFile:56)
	at com.yandex.mobile.ads.impl.hj0.b(SourceFile:68)
	at com.yandex.mobile.ads.impl.cw1.b(SourceFile:2)
	at com.yandex.mobile.ads.impl.ka2.a(SourceFile:22)
	at com.yandex.mobile.ads.banner.b.a(SourceFile:36)
	at com.yandex.mobile.ads.impl.vd.a(SourceFile:5)
	at com.yandex.mobile.ads.impl.fb0$b.run(SourceFile:32)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8248)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)

**Comment by mobile-ads-github** [comment]
Здравствуйте, подскажите пожалуйста версию SDK

**Comment by NikiHard** [comment]
На 5.5.0 точно есть, 5.5.1 еще не пробовал

**Comment by NikiHard** [comment]
Точно не скажу, по моему вся 5 версия. Это как то связано с медиацией в admob, когда увеличиваю показ рекламы Яндекса то количество ошибок растёт
