### ISSUE TITLE
NativeAdException: Resource for required view feedback is not present

### ISSUE THREAD

**Issue by Jovandine** [yandexmobile/yandex-ads-sdk-android#192]
Добрый день
Наблюдаем сильный рост количества вылетов в рекламной карусели (SliderAd)
yandexMetricaPushVersion=2.0.0
yandexMetricaVersion=5.0.0
yandexAdsVersion=5.3.2
yandexMediationAdMobVersion=21.2.0.0
yandexMediationMyTargetVersion=5.15.0.2

![Screenshot 2023-02-27 at 09 41 32](https://user-images.githubusercontent.com/8447884/221467714-c8c8aed3-6b92-45a0-bc7c-0e20fd4ef2d9.png)

Caused by com.yandex.mobile.ads.nativeads.NativeAdException: Resource for required view feedback is not present
       at com.yandex.mobile.ads.nativeads.aw.a(SourceFile:1242)
       at com.yandex.mobile.ads.nativeads.v.a(SourceFile:142)
       at com.yandex.mobile.ads.nativeads.v.bindNativeAd(SourceFile:122)
       at kz.kolesa.ui.adapter.advertlist.nativead.presentation.adapter.MultipleNativeAdItemViewHolder.bind(MultipleNativeAdItemViewHolder.kt:36)
       at kz.kolesa.ui.adapter.advertlist.nativead.presentation.adapter.MultipleNativeAdAdapter.onBindViewHolder(MultipleNativeAdAdapter.kt:44)
       at kz.kolesa.ui.adapter.advertlist.nativead.presentation.adapter.MultipleNativeAdAdapter.onBindViewHolder(MultipleNativeAdAdapter.kt:13)
       at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
       at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
       at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
       at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
       at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:288)
       at androidx.recyclerview.widget.GapWorker.prefetchInnerRecyclerViewWithDeadline(GapWorker.java:335)
       at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:351)
       at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:361)
       at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:368)
       at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:399)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:226)
       at android.app.ActivityThread.main(ActivityThread.java:7592)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by Jovandine** [comment]
судя по падающим версиям приложения там были более старые библиотеки яндекс-рекламы.

**Comment by mobile-ads-github** [comment]
Добрый день! С версии sdk 5.2.0 feedback стал обязательным ассетом. Вам необходимо предоставить для него view.
[Пример](https://yandex.ru/dev/mobile-ads/doc/android/quick-start/native-ad.html#view-ad__manual) интеграции.

**Comment by Jovandine** [comment]
Мы давно добавили его, еще в августе. На тот момент версия библиотеки была yandexAdsVersion=5.1.1
Получается проблема в том, что падает приложение без этого ассета на версии mobileads до 5.1.1
