### ISSUE TITLE
java.lang.RuntimeException at com.yandex.mobile.ads.impl.nq0.a(SourceFile:4) (mobileads:5.5.1)

### ISSUE THREAD

**Issue by DimaKoz** [yandexmobile/yandex-ads-sdk-android#197]
```
mobileads:5.5.1
mobmetricalib:5.2.0
```

```
Drawable ru.my:drawable/yandex_ads_video_progress_bar_background has unresolved theme attributes! 
Consider using Resources.getDrawable(int, Theme) or Context.getDrawable(int).
java.lang.RuntimeException at android.content.res.Resources.getDrawable(Resources.java:967)
at com.yandex.mobile.ads.impl.nq0.a(SourceFile:4)
at com.yandex.mobile.ads.impl.bc1.a(SourceFile:1)
at com.yandex.mobile.ads.impl.yj0.a(SourceFile:8)
at com.yandex.mobile.ads.impl.ya0.a(SourceFile:5)
at com.yandex.mobile.ads.impl.ph1.a(SourceFile:10)
at com.yandex.mobile.ads.impl.ta0.a(SourceFile:2)
at com.yandex.mobile.ads.impl.aa.a(SourceFile:6)
at com.yandex.mobile.ads.impl.ba.a(SourceFile:12)
at com.yandex.mobile.ads.nativeads.w.<init>(SourceFile:13)
at com.yandex.mobile.ads.nativeads.l0.a(SourceFile:14)
at com.yandex.mobile.ads.nativeads.m.bindNativeAd(SourceFile:6)
at ru.my.Holder.displayControls(Holder.kt:154)
at ru.my.Holder.onAdLoaded(Holder.kt:223)
at ru.my.listener.NativeAdLoadListener.onAdLoaded(NativeAdLoadListener.kt:13)
at com.yandex.mobile.ads.nativeads.t.a(SourceFile:14)
at com.yandex.mobile.ads.nativeads.t.$r8$lambda$YhpTySBNlf8AQXfqKYJX-vKgziI(Unknown Source:0)
at com.yandex.mobile.ads.nativeads.t$$ExternalSyntheticLambda3.run(Unknown Source:4)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8757)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

**Comment by mobile-ads-github** [comment]
Спасибо за репорт, мы проверим и вернемся!

**Comment by mobile-ads-github** [comment]
Здравствуйте, @DimaKoz,

К сожалению проблемe воспроизвести пока не удалось. Не могли бы вы предоставить дополнительную информацию, а именно:
1. Версию Android API на которой словили ошибку?
2. Эмулятор или реальны девайс? Если реальный девайс, то какая модель?
3. Какой тип рекламы пытались загрузить (rewarded, interstitial, native, banner)?

Спасибо!

**Comment by DimaKoz** [comment]
Тип рекламы - у нас используется разная, native 90% от общего кол-ва, есть banner, но их очень мало  и в тот момент были возможны только нативные баннеры на экране.
Устройство было реальным 100%, не рут, прошло много времени, не вспомню точно, какое устройство у меня было тестовым на тот момент, скорее всего, Самсунг SM-G965F(андроид 10)
В логах у себя увидел вывод креша(был обернут try/catch, он никуда не отправляется).
Судя по крешу, когда в нативном баннере видео проигрывается(или загружается), на некоторых устройствах возникает проблема с ресурсом yandex_ads_video_progress_bar_background прогрессбара на видео из SDK.

<img width="970" alt="Снимок экрана 2023-03-29 в 16 19 28" src="https://user-images.githubusercontent.com/3092276/228551080-d192af8c-7d8f-4fb4-8d53-97bde75be6ea.png">

**Comment by mobile-ads-github** [comment]
Добрый день. Данная проблема была исправлена в версии рекламного SDK 5.8.0. Обновление версии SDK должно помочь.

**Comment by DimaKoz** [comment]
Спасибо
