### ISSUE TITLE
ArithmeticException: divide by zero at com.yandex.mobile.ads.impl.jc.a(jc.java:10)(mobileads:5.5.1)

### ISSUE THREAD

**Issue by DimaKoz** [yandexmobile/yandex-ads-sdk-android#198]
```
mobileads:5.5.1
mobmetricalib:5.2.0
```

```
Fatal Exception: java.lang.ArithmeticException: divide by zero
       at com.yandex.mobile.ads.impl.jc.a(jc.java:10)
       at com.yandex.mobile.ads.impl.rz0.a(rz0.java:26)
       at com.yandex.mobile.ads.impl.rz0.$r8$lambda$sdBzvSbjP_4x1bPBEdbndNihP-s(rz0.java)
       at com.yandex.mobile.ads.impl.rz0$$InternalSyntheticLambda$1$dd8866ed40473b80855784cc83003ecfd91155b1325771a9a3d93cb2f2d96881$0.run(rz0.java:6)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:8057)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
```
<img width="149" alt="Снимок экрана 2023-03-29 в 16 40 22" src="https://user-images.githubusercontent.com/3092276/228556804-3c131494-1ce4-40c6-a510-1a0c9df666f0.png">
<img width="160" alt="Снимок экрана 2023-03-29 в 16 40 05" src="https://user-images.githubusercontent.com/3092276/228556819-88336f76-bb5d-4df1-8fd2-1566d7f037ff.png">

**Comment by mobile-ads-github** [comment]
Спасибо за обращение, разбираемся
