### ISSUE TITLE
Increased errors after Yandex integration

### ISSUE THREAD

**Issue by lucasrafagnin** [yandexmobile/yandex-ads-sdk-android#218]
I integrated with the Yandex SDK through AppLovin MAX in the latest version of my app, and then there were new errors in the app's Crashlytics.

The error is the following:

```
Fatal Exception: android.database.sqlite.SQLiteException: table httpauth already exists (code 1 SQLITE_ERROR[1])
       at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:1222)
       at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:756)
       at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:67)
       at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:2629)
       at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:2550)
       at yF.c(chromium-TrichromeWebViewGoogle.aab-stable-573522731:62)
       at xF.run(chromium-TrichromeWebViewGoogle.aab-stable-573522731:16)
```

And with references to classes from Yandex:

```
YandexMobileAds.BaseController:
       at jdk.internal.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1063)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1123)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)
```

As it is happening with a large number of users, I preferred to disable the integration momentarily.

Any idea what's going on?

**Comment by mobile-ads-github** [comment]
Hello!
Could you please give us a bit more information?
We'd like to know:
- Your versions of AppLovinSDK and AppLovinMediationYandexAdapter
- App Id to check possible error logs. 

<details><summary>If you don't want to share them in public, send to our email</summary>
<p>
mobile-ads-github@yandex-team.ru
</p>
</details> 

Thank you for the report

**Comment by mobile-ads-github** [comment]
Could you also provide us with the following information?
1) Is there any specificity to the error (e.g. is it reproduced only on certain devices or android versions)?
2) Stack trace of each thread given in Crashlytics for this error

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-2234. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-2234 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Hi! Is everything working stably now?

**Comment by XJIOP** [comment]
Такая же проблема, постоянно эта ошибка вылазит в логах
`SQLiteException: table httpauth already exists`

<img width="698" alt="Снимок экрана 2024-01-22 041300" src="https://github.com/yandexmobile/yandex-ads-sdk-android/assets/1385503/c55a4e29-af66-401b-9f37-87b06fffd235">
<img width="706" alt="Снимок экрана 2024-01-22 041226" src="https://github.com/yandexmobile/yandex-ads-sdk-android/assets/1385503/5b87141c-b662-4311-bbde-991dc6fe88ab">

**Comment by mobile-ads-github** [comment]
Добрый день! Обработка данной системной ошибки исправлена в версии 5.7.0. Если ошибка воспроизводится, рекомендуем обновить версию SDK.
