### ISSUE TITLE
java.lang.NullPointerException  com.monetization.ads.banner.a.onVisibilityChanged (v6.3.0, android 5)

### ISSUE THREAD

**Issue by slgitcode** [yandexmobile/yandex-ads-sdk-android#248]
При обновлении на версию 6.3.0 появился постоянный креш при добавлении баннерной рекламы на android 5, 5.1.1.
В версии 6.2.0 креша не было.

java.lang.RuntimeException: Unable to start activity ComponentInfo: android.view.InflateException: Binary XML file line #24: Error inflating class com.yandex.mobile.ads.banner.BannerAdView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2455)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2517)
	at android.app.ActivityThread.access$800(ActivityThread.java:162)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1412)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:189)
	at android.app.ActivityThread.main(ActivityThread.java:5529)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)
Caused by: android.view.InflateException: Binary XML file line #24: Error inflating class com.yandex.mobile.ads.banner.BannerAdView
	at android.view.LayoutInflater.createView(LayoutInflater.java:633)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:916)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:802)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:775)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:197)
	at ...MainActivity.onCreate(MainActivity.kt:39)
	at android.app.Activity.performCreate(Activity.java:5977)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2408)
	... 10 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
	at android.view.LayoutInflater.createView(LayoutInflater.java:607)
	... 25 more
Caused by: java.lang.NullPointerException: Attempt to invoke a virtual method on a null object reference
	at com.monetization.ads.banner.a.onVisibilityChanged(SourceFile:3)
	at android.view.View.dispatchVisibilityChanged(View.java:8757)
	at android.view.ViewGroup.dispatchVisibilityChanged(ViewGroup.java:1273)
	at android.view.View.setFlags(View.java:9847)
	at android.view.View.<init>(View.java:4186)
	at android.view.ViewGroup.<init>(ViewGroup.java:513)
	at android.widget.RelativeLayout.<init>(RelativeLayout.java:262)
	at android.widget.RelativeLayout.<init>(RelativeLayout.java:258)
	at com.monetization.ads.banner.a.<init>(SourceFile:7)
	at com.monetization.ads.banner.a.<init>(SourceFile:6)
	at com.monetization.ads.banner.a.<init>(SourceFile)
	at com.yandex.mobile.ads.banner.BannerAdView.<init>(SourceFile:3)
	at com.yandex.mobile.ads.banner.BannerAdView.<init>(SourceFile:2)
	... 28 more

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-2806. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-2806 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Добрый день! Можете подсказать, на каких устройствах стабильно воспроизводится проблема?

**Comment by slgitcode** [comment]
![2024-01-19_18-35-02](https://github.com/yandexmobile/yandex-ads-sdk-android/assets/136124373/9fa7873e-9996-475d-bf69-b9afa0390bf7)
![2024-01-19_18-41-13](https://github.com/yandexmobile/yandex-ads-sdk-android/assets/136124373/2c0d142b-d64c-43c7-a273-228fc9a2bf6a)

Также стабильно на эмуляторе от Genymotion воспроизводится на android 5.

**Comment by mobile-ads-github** [comment]
Добрый день! Изучаем ситуацию. Вернемся, как будет информация.

**Comment by mobile-ads-github** [comment]
Добрый день! Обнаружили проблему на своей стороне, спасибо за помощь. Исправим в ближайшем релизе.
