### ISSUE TITLE
android.renderscript.RSIllegalArgumentException: Unsupported element type.

### ISSUE THREAD

**Issue by hexep** [yandexmobile/yandex-ads-sdk-android#256]
Версия mobileads - 6.4.0

```
android.renderscript.RSIllegalArgumentException: Unsupported element type.
	at android.renderscript.ScriptIntrinsicBlur.setInput(ScriptIntrinsicBlur.java:67)
	at com.yandex.div.core.view2.divs.widgets.ImageUtilsKt.getBlurredBitmap(ImageUtilsKt.java:86)
	at com.yandex.div.core.view2.divs.widgets.ImageUtilsKt.applyFilters(ImageUtilsKt.java:47)
	at com.yandex.div.core.view2.divs.DivImageBinder.applyFiltersAndSetBitmap(DivImageBinder.java:106)
	at com.yandex.div.core.view2.divs.DivImageBinder.access$isHighPriorityShow(DivImageBinder.java:28)
	at com.yandex.div.core.view2.divs.DivImageBinder.access$applyFiltersAndSetBitmap(DivImageBinder.java:28)
	at com.yandex.div.core.view2.divs.DivImageBinder$applyImage$reference$1.onSuccess(DivImageBinder$applyImage$reference.java:186)
	at com.yandex.mobile.ads.impl.wt$b.a(wt.java:6)
	at com.yandex.mobile.ads.impl.k60.run(k60.java:12)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8349)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
```

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-3025. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-3025 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Добрый день! Данную проблему поправили, спасибо за обращение!
