### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException

### ISSUE THREAD

**Issue by goldfish07** [yandexmobile/yandex-ads-sdk-android#276]
Crash Occur in Android 13 only 
i am using 

>     implementation 'com.yandex.android:mobileads:7.2.0'
>     implementation 'com.yandex.ads.mediation:mobileads-unityads:4.12.0.0'
>     implementation 'com.yandex.ads.mediation:mobileads-ironsource:8.1.0.1'

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.app/com.yandex.mobile.ads.common.AdActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x7f080282
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

```
          Caused by android.content.res.Resources$NotFoundException: Resource ID #0x7f080282
       at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:224)
       at android.content.res.Resources.getDrawableForDensity(Resources.java:876)
       at android.content.res.XResources.getDrawableForDensity(XResources.java:868)
       at android.content.res.Resources.getDrawable(Resources.java:819)
       at android.content.res.XResources.getDrawable(XResources.java:790)
       at android.content.Context.getDrawable(Context.java:605)
       at androidx.core.content.ContextCompat$Api21Impl.getDrawable(ContextCompat.java)
       at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java)
       at com.yandex.mobile.ads.impl.of1.a(SourceFile:23)
       at com.yandex.mobile.ads.impl.mf1.a(SourceFile:13)
       at com.yandex.mobile.ads.impl.d0.a(SourceFile:26)
       at com.yandex.mobile.ads.impl.w31.a(:27)
       at com.yandex.mobile.ads.impl.jq0.a(SourceFile:23)
       at com.yandex.mobile.ads.impl.ml1.a(SourceFile:61)
       at com.yandex.mobile.ads.impl.eq0.a(SourceFile:39)
       at com.yandex.mobile.ads.impl.fd.a(SourceFile:10)
       at com.yandex.mobile.ads.impl.gd.a(SourceFile:21)
       at com.yandex.mobile.ads.impl.kz0.<init>(SourceFile:41)
       at com.yandex.mobile.ads.impl.d11.a(SourceFile:73)
       at com.yandex.mobile.ads.impl.dy0.b(SourceFile:147)
       at com.yandex.mobile.ads.impl.sx0.a(SourceFile:49)
       at com.yandex.mobile.ads.impl.u70.a(SourceFile:37)
       at com.yandex.mobile.ads.impl.an.a(SourceFile:12)
       at com.yandex.mobile.ads.impl.hk0.a(SourceFile:8)
       at com.yandex.mobile.ads.impl.lk0.a(SourceFile:25)
       at com.yandex.mobile.ads.impl.w70.c(SourceFile:14)
       at com.yandex.mobile.ads.impl.g1.c(SourceFile:70)
       at com.yandex.mobile.ads.impl.x0.b(SourceFile:21)
       at com.yandex.mobile.ads.common.AdActivity.onCreate(SourceFile:52)
       at android.app.Activity.performCreate(Activity.java:7009)
       at android.app.Activity.performCreate(Activity.java:7000)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-3540. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-3540 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by goldfish07** [comment]
any update on this issue ?

**Comment by mobile-ads-github** [comment]
We apologize for the long wait. We are trying to reproduce the issue. Does this occur in the new versions of the SDK?

**Comment by mobile-ads-github** [comment]
We have closed the ticket due to a lack of response.
