### ISSUE TITLE
FATAL EXCEPTION: java.lang.RuntimeException: Unable to resume activity

### ISSUE THREAD

**Issue by bit-world** [yandexmobile/yandex-ads-sdk-android#279]
Произвольно крашится приложение при вызове **onResume**

![21312321321321321](https://github.com/user-attachments/assets/a0c39c88-c43c-40c1-b328-bca4ae1ceaff)

```
java.lang.RuntimeException: Unable to resume activity {activity.zzz}: java.lang.ClassCastException: com.monetization.ads.nativeads.CustomizableMediaView cannot be cast to elements.ProgressIndicator
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4773)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4806)
at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7872)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.ClassCastException: com.monetization.ads.nativeads.CustomizableMediaView cannot be cast to elements.ProgressIndicator
at activity.act_list.invalidate(act_list.java:43)
at activity.act_list.onResume(act_list.java:54)
at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1564)
at android.app.Activity.performResume(Activity.java:8437)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4763)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4806) 
at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54) 
at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45) 
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307) 
at android.os.Handler.dispatchMessage(Handler.java:106) 
at android.os.Looper.loopOnce(Looper.java:201) 
at android.os.Looper.loop(Looper.java:288) 
at android.app.ActivityThread.main(ActivityThread.java:7872) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 
```

**Comment by bit-world** [comment]
Версия SDK актуальная
`implementation 'com.yandex.android:mobileads:7.4.0'`

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-3672. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-3672 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Здравствуйте.

Уточните, возникает ли данная ошибка с последней версией SDK. Для какого типа рекламы возникает ошибка?

**Comment by bit-world** [comment]
В новой версии всё работает отлично
