### ISSUE TITLE
Краш у Vungle на телефонах без гугл сервисов.

### ISSUE THREAD

**Issue by stayf** [yandexmobile/yandex-ads-sdk-android#288]
Использую `com.yandex.android:mobileads:7.6.0` и добавил недавно `com.yandex.ads.mediation:mobileads-vungle:7.4.1.0`
Выложил сборку в рустор. И полетели краши у телефонов без гугл плей сервисов.
Девайсы: Realme 11, CTR-L81, ADY-LX9, Legion Y70, BV5200 Pro, S98Pro
Краш прям критический, прошу обратить внимание и пофиксить оперативно или подсказать, что мне сделать, чтобы его убрать на телефонах без плей сервисов.
```
          Fatal Exception: java.io.IOException: Google Play services not available
       at com.google.android.gms.ads.identifier.AdvertisingIdClient.zzb(com.google.android.gms:play-services-ads-identifier@@17.1.0:21)
       at com.google.android.gms.ads.identifier.AdvertisingIdClient.getAdvertisingIdInfo(com.google.android.gms:play-services-ads-identifier@@17.1.0:3)
       at com.vungle.ads.internal.platform.AndroidPlatform.getGoogleAdvertisingInfo(AndroidPlatform.kt:102)
       at com.vungle.ads.internal.platform.AndroidPlatform.getAdvertisingInfo(AndroidPlatform.kt:127)
       at com.vungle.ads.internal.network.VungleApiClient.getDeviceBody$vungle_ads_release(VungleApiClient.kt:652)
       at com.vungle.ads.internal.network.VungleApiClient.getDeviceBody(VungleApiClient.kt:636)
       at com.vungle.ads.internal.network.VungleApiClient.requestBody(VungleApiClient.kt:626)
       at com.vungle.ads.internal.network.VungleApiClient.requestAd(VungleApiClient.kt:339)
       at com.vungle.ads.internal.load.DefaultAdLoader.fetchAdMetadata(DefaultAdLoader.kt:58)
       at com.vungle.ads.internal.load.DefaultAdLoader.requestAd(DefaultAdLoader.kt:43)
       at com.vungle.ads.internal.load.BaseAdLoader.loadAd$lambda-0(BaseAdLoader.kt:203)
       at com.vungle.ads.internal.executor.VungleThreadPoolExecutor$Companion.wrapRunnableWithFail(VungleThreadPoolExecutor.kt:36)
       at com.vungle.ads.internal.executor.VungleThreadPoolExecutor$Companion.access$wrapRunnableWithFail(VungleThreadPoolExecutor.kt:31)
       at com.vungle.ads.internal.executor.VungleThreadPoolExecutor$Companion$getWrappedRunnableWithFail$2.run(VungleThreadPoolExecutor.kt:67)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at java.lang.Thread.run(Thread.java:1012)
        
```

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-3924. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-3924 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Добрый день! Передали в разработку, изучаем кейс

**Comment by stayf** [comment]
@mobile-ads-github Добрый день. Да, все хорошо. Краша нет. Спасибо!
