### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method void android.view.View.unFocus

### ISSUE THREAD

**Issue by XJIOP** [yandexmobile/yandex-ads-sdk-android#291]
targetSdk 35
compileSdk = 35
com.android.tools.build:gradle:8.7.3

это происходит в версии
implementation 'com.yandex.android:mobileads:7.6.0'
и
implementation 'com.yandex.android:mobileads:7.9.0'

Version: Android 13
Brand: Oppo
Model: RMX3834

```
Fatal Exception: java.lang.RuntimeException: Unable to destroy activity {.../com.yandex.mobile.ads.common.AdActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.unFocus(android.view.View)' on a null object reference
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5543)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5576)
       at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:178)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:99)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2393)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:8061)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:703)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:923)
```

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.unFocus(android.view.View)' on a null object reference
       at android.view.ViewGroup.removeAllViewsInLayout(ViewGroup.java:5861)
       at android.view.ViewGroup.removeAllViews(ViewGroup.java:5820)
       at com.yandex.mobile.ads.impl.qm0.a(SourceFile:31)
       at com.yandex.mobile.ads.impl.um0.b(SourceFile:33)
       at com.yandex.mobile.ads.impl.c6.invalidate(SourceFile:173)
       at com.yandex.mobile.ads.impl.h1.d(SourceFile:122)
       at com.yandex.mobile.ads.impl.y0.a(SourceFile:59)
       at com.yandex.mobile.ads.common.AdActivity.onDestroy(SourceFile:1)
       at android.app.Activity.performDestroy(Activity.java:8585)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1419)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5530)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5576)
       at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:178)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:99)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2393)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:8061)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:703)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:923)
```

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером ADLIBGITHUB-2. Мы ознакомимся и вернемся с ответом как можно скорее, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number ADLIBGITHUB-2 has been created for analysis. We will get acquainted and return with the answer as soon as possible, we may request additional information.

**Comment by mobile-ads-github** [comment]
Здравствуйте! 

В версии 7.10 мы добавили логирование данной ошибки.
Если актуально, пришлите, пожалуйста, новый полный стектрейс для последующего дебага.
