### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo

### ISSUE THREAD

**Issue by nazirjonmakhmadkulov** [yandexmobile/yandex-ads-sdk-android#295]
implementation 'com.yandex.android:mobileads:7.6.0'  
  
Brand:Samsung
Model:Galaxy S20+ 5G
Version:Android 9

Brand:Oneplus
Model:CPH2569
Version:Android 13

  Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.app/com.yandex.mobile.ads.common.AdActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x7f070137
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6718)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером ADLIBGITHUB-9. Мы ознакомимся и вернемся с ответом как можно скорее, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number ADLIBGITHUB-9 has been created for analysis. We will get acquainted and return with the answer as soon as possible, we may request additional information.

**Comment by mobile-ads-github** [comment]
Ошибка была исправлена в предыдущих версиях Mobile SDK.
