### ISSUE TITLE
OutOfMemoryError: java.util.HashMap$HashMapEntry[] of length 1073741824 would overflow at com.yandex.mobile.ads.network.core.f.d (SourceFile:556)

### ISSUE THREAD

**Issue by DimaKoz** [yandexmobile/yandex-ads-sdk-android#3]
В версиях библиотек:

``` Groovy
compile 'com.yandex.android:mobmetricalib:2.41'
compile 'com.yandex.android:mobileads:2.20'
```

Fatal Exception: java.lang.OutOfMemoryError: java.util.HashMap$HashMapEntry[] of length 1073741824 would overflow
       at java.util.HashMap.makeTable(HashMap.java:550)
       at java.util.HashMap.<init>(HashMap.java:158)
       at com.yandex.mobile.ads.network.core.f.d(SourceFile:556)
       at com.yandex.mobile.ads.network.core.f$a.a(SourceFile:401)
       at com.yandex.mobile.ads.network.core.f.a(SourceFile:154)
       at com.yandex.mobile.ads.network.core.d.run(SourceFile:84)

**Comment by DimaKoz** [comment]
Происходит в той же строчке кода:

Fatal Exception: java.lang.IllegalArgumentException: Capacity: -2013265910
       at java.util.HashMap.<init>(HashMap.java:140)
       at com.yandex.mobile.ads.network.core.f.d(SourceFile:556)
       at com.yandex.mobile.ads.network.core.f$a.a(SourceFile:401)
       at com.yandex.mobile.ads.network.core.f.a(SourceFile:154)
       at com.yandex.mobile.ads.network.core.d.run(SourceFile:84)

**Comment by satsakul** [comment]
Благодарим Вас за предоставленную информацию.
Мы внимательно ознакомились с проблемами, описанными Вами, и пришли к выводу, что корень у них один и тот же.
Проанализировав наши данные, мы установили, что проблема воспроизводится на весьма ограниченном числе устройств. 
Тем не менее, мы постараемся решить данную проблему в одной из следующих версий SDK.

**Comment by satsakul** [comment]
Проблема исправлена в версии mobileads-2.51
