### ISSUE TITLE
Ad Activity into the AndroidManifest.xml is integrated wrong

### ISSUE THREAD

**Issue by nikitoSha** [yandexmobile/yandex-ads-sdk-android#30]
Вынес ошибку отдельно. 

	Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{ru.rsit.iamspecialist/ru.rsit.iamspecialist.main}: java.lang.IllegalStateException: Ad Activity into the AndroidManifest.xml is integrated wrong
		   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2245)
		   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2299)
		   at android.app.ActivityThread.access$700(ActivityThread.java:150)
		   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1280)
		   at android.os.Handler.dispatchMessage(Handler.java:99)
		   at android.os.Looper.loop(Looper.java:137)
		   at android.app.ActivityThread.main(ActivityThread.java:5283)
		   at java.lang.reflect.Method.invokeNative(Method.java)
		   at java.lang.reflect.Method.invoke(Method.java:511)
		   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
		   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
		   at dalvik.system.NativeStart.main(NativeStart.java)

	Caused by java.lang.IllegalStateException: Ad Activity into the AndroidManifest.xml is integrated wrong
		   at com.yandex.mobile.ads.impl.ab.a(SourceFile:113)
		   at com.yandex.mobile.ads.InterstitialAd.<init>(SourceFile:36)
		   **at ru.rsit.iamspecialist.main.onCreate(main.java:201)**
		   at android.app.Activity.performCreate(Activity.java:5283)
		   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097)
		   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2209)
		   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2299)
		   at android.app.ActivityThread.access$700(ActivityThread.java:150)
		   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1280)
		   at android.os.Handler.dispatchMessage(Handler.java:99)
		   at android.os.Looper.loop(Looper.java:137)
		   at android.app.ActivityThread.main(ActivityThread.java:5283)

Вылетает на строке в методе OnCreate() главной активности:

    mInterstitialAd = new InterstitialAd(app_context);

http://crashes.to/s/ba65fbefb69

**Comment by dmitryfisko** [comment]
Добрый день. Подскажите, проблема воспроизводится стабильно или вероятностно?
Вы подключаете библиотеку через AAR или JAR?
Инструкция по интеграции SDK через JAR и AAR есть на следующей странице документации:
https://tech.yandex.ru/mobile-ads/doc/dg/android/quick-start/android-ads-component-docpage/

**Comment by tameronlan** [comment]
Добрый день. Библиотека подключена была через AAR. У меня не воспроизводилась, но у пользователей возникала проблема достаточно часто (смотрел по fabric). Вчера обновил версии бибдиотек до 2.80 и 3.4.0 соответственно, ошибки ушли.

**Comment by satsakul** [comment]
Спасибо
