### ISSUE TITLE
Ошибка инициализации Protocol TLSv1 is not supported в Android 15

### ISSUE THREAD

**Issue by maxim-yudin** [yandexmobile/yandex-ads-sdk-android#300]
Начали получать при запуске приложения видимо при инициализации SDK на Android 15.

<img width="495" alt="Screenshot 2024-12-24 at 9 02 38 AM" src="https://github.com/user-attachments/assets/7f6889bd-3d82-4897-82f5-7dfea2c6efdb" />

Fatal Exception: kotlinx.coroutines.CompletionHandlerException: Exception in invokeOnCancellation handler for CancellableContinuation(DispatchedContinuation[java.util.concurrent.Executors$AutoShutdownDelegatedExecutorService@ed98848, Continuation at com.monetization.ads.base.SdkConfigurationLoaderHolder$loadSdkConfiguration$2.invokeSuspend(SdkConfigurationLoaderHolder.kt)@db2d119]){Cancelled}@32ed5de
       at kotlinx.coroutines.CancellableContinuationImpl.callCancelHandler(CancellableContinuationImpl.kt:711)
       at kotlinx.coroutines.CancellableContinuationImpl.cancel(CancellableContinuationImpl.kt:209)
       at kotlinx.coroutines.CancellableContinuationImpl.parentCancelled$kotlinx_coroutines_core(CancellableContinuationImpl.kt:221)
       at kotlinx.coroutines.ChildContinuation.invoke(CancellableContinuationImpl.kt:698)
       at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1604)
       at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:931)
       at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:894)
       at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:859)
       at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:104)
       at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:164)
       at kotlinx.coroutines.BuildersKt.withContext(Builders.kt:1)
       at com.yandex.mobile.ads.impl.qo1.a(SourceFile:48)
       at com.yandex.mobile.ads.impl.pp1.b(SourceFile:284)
       at com.yandex.mobile.ads.impl.pp1$b.invokeSuspend(SourceFile:204)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:266)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:100)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1156)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:651)
       at java.lang.Thread.run(Thread.java:1117)

Caused by java.lang.IllegalArgumentException: protocol TLSv1 is not supported
       at com.android.org.conscrypt.NativeCrypto.checkEnabledProtocols(NativeCrypto.java:1187)
       at com.android.org.conscrypt.SSLParametersImpl.<init>(SSLParametersImpl.java:160)
       at com.android.org.conscrypt.OpenSSLContextImpl.engineInit(OpenSSLContextImpl.java:123)
       at javax.net.ssl.SSLContext.init(SSLContext.java:326)
       at com.yandex.mobile.ads.impl.hn1.a(SourceFile:197)
       at com.yandex.mobile.ads.impl.ee0.a(SourceFile:2)
       at com.yandex.mobile.ads.impl.ok1.a(SourceFile:35)
       at com.yandex.mobile.ads.impl.c81.a(SourceFile:19)
       at com.yandex.mobile.ads.impl.lk1.a(SourceFile:10)
       at com.yandex.mobile.ads.impl.po1.a(SourceFile:53)
       at com.yandex.mobile.ads.impl.qo1$a$a.invoke(SourceFile:34)
       at kotlinx.coroutines.CancelHandler$UserSupplied.invoke(CancellableContinuationImpl.kt:667)
       at kotlinx.coroutines.CancellableContinuationImpl.callCancelHandler(CancellableContinuationImpl.kt:239)
       at kotlinx.coroutines.CancellableContinuationImpl.cancel(CancellableContinuationImpl.kt:209)
       at kotlinx.coroutines.CancellableContinuationImpl.parentCancelled$kotlinx_coroutines_core(CancellableContinuationImpl.kt:221)
       at kotlinx.coroutines.ChildContinuation.invoke(CancellableContinuationImpl.kt:698)
       at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1604)
       at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:931)
       at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:894)
       at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:859)
       at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:104)
       at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:164)
       at kotlinx.coroutines.BuildersKt.withContext(Builders.kt:1)
       at com.yandex.mobile.ads.impl.qo1.a(SourceFile:48)
       at com.yandex.mobile.ads.impl.pp1.b(SourceFile:284)
       at com.yandex.mobile.ads.impl.pp1$b.invokeSuspend(SourceFile:204)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:266)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:100)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1156)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:651)
       at java.lang.Thread.run(Thread.java:1117)

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером ADLIBGITHUB-17. Мы ознакомимся и вернемся с ответом как можно скорее, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number ADLIBGITHUB-17 has been created for analysis. We will get acquainted and return with the answer as soon as possible, we may request additional information.

**Comment by XJIOP** [comment]
com.yandex.android:mobileads:7.8.1

Brand: Google
Model: Pixel 6
Version: Android 15

```
Fatal Exception: kotlinx.coroutines.CompletionHandlerException: Exception in invokeOnCancellation handler for CancellableContinuation(DispatchedContinuation[java.util.concurrent.Executors$AutoShutdownDelegatedExecutorService@38917d8, Continuation at com.monetization.ads.base.SdkConfigurationLoaderHolder$loadSdkConfiguration$2.invokeSuspend(SdkConfigurationLoaderHolder.kt)@463d984]){Cancelled}@ae2056d
       at kotlinx.coroutines.CancellableContinuationImpl.callCancelHandler(CancellableContinuationImpl.kt:683)
       at kotlinx.coroutines.CancellableContinuationImpl.cancel(CancellableContinuationImpl.kt:212)
       at kotlinx.coroutines.CancellableContinuationImpl.parentCancelled$kotlinx_coroutines_core(CancellableContinuationImpl.kt:224)
       at kotlinx.coroutines.ChildContinuation.invoke(JobSupport.kt:1447)
       at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1474)
       at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:903)
       at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:866)
       at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:831)
       at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:183)
       at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
       at kotlinx.coroutines.BuildersKt.withContext(Builders.kt:1)
       at com.yandex.mobile.ads.impl.bp1.a(SourceFile:57)
       at com.yandex.mobile.ads.impl.aq1.b(SourceFile:248)
       at com.yandex.mobile.ads.impl.aq1$b.invokeSuspend(SourceFile:183)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:270)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1156)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:651)
       at java.lang.Thread.run(Thread.java:1117)
```

```
Caused by java.lang.IllegalArgumentException: protocol TLSv1 is not supported
       at com.android.org.conscrypt.NativeCrypto.checkEnabledProtocols(NativeCrypto.java:1187)
       at com.android.org.conscrypt.SSLParametersImpl.<init>(SSLParametersImpl.java:160)
       at com.android.org.conscrypt.OpenSSLContextImpl.engineInit(OpenSSLContextImpl.java:123)
       at javax.net.ssl.SSLContext.init(SSLContext.java:326)
       at com.yandex.mobile.ads.impl.sn1.a(SourceFile:197)
       at com.yandex.mobile.ads.impl.le0.a(SourceFile:2)
       at com.yandex.mobile.ads.impl.zk1.a(SourceFile:35)
       at com.yandex.mobile.ads.impl.l81.a(SourceFile:33)
       at com.yandex.mobile.ads.impl.wk1.a(SourceFile:10)
       at com.yandex.mobile.ads.impl.ap1.a(SourceFile:57)
       at com.yandex.mobile.ads.impl.bp1$a$a.invoke(SourceFile:42)
       at kotlinx.coroutines.InvokeOnCancel.invoke(CancellableContinuationImpl.kt:642)
       at kotlinx.coroutines.CancellableContinuationImpl.callCancelHandler(CancellableContinuationImpl.kt:249)
       at kotlinx.coroutines.CancellableContinuationImpl.cancel(CancellableContinuationImpl.kt:212)
       at kotlinx.coroutines.CancellableContinuationImpl.parentCancelled$kotlinx_coroutines_core(CancellableContinuationImpl.kt:224)
       at kotlinx.coroutines.ChildContinuation.invoke(JobSupport.kt:1447)
       at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1474)
       at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:903)
       at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:866)
       at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:831)
       at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:183)
       at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
       at kotlinx.coroutines.BuildersKt.withContext(Builders.kt:1)
       at com.yandex.mobile.ads.impl.bp1.a(SourceFile:57)
       at com.yandex.mobile.ads.impl.aq1.b(SourceFile:248)
       at com.yandex.mobile.ads.impl.aq1$b.invokeSuspend(SourceFile:183)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:270)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1156)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:651)
       at java.lang.Thread.run(Thread.java:1117)
```

**Comment by mobile-ads-github** [comment]
Здравствуйте! 
Уточните, пожалуйста,  версии targetSDK, compileSDK и BuildToolsVersion.

**Comment by XJIOP** [comment]
targetSdk 35
compileSdk = 35
com.android.tools.build:gradle:8.7.3

**Comment by mobile-ads-github** [comment]
Добрый день.

Исправление будет в релизе SDK 7.12.0
