### ISSUE TITLE
Не работает с Android 9

### ISSUE THREAD

**Issue by slavakraynov** [yandexmobile/yandex-ads-sdk-android#33]
implementation 'com.yandex.android:mobmetricalib:3.2.2'
implementation 'com.yandex.android:mobileads:2.72'

    java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/ProtocolVersion;

        at com.yandex.mobile.ads.impl.lg.a(SourceFile:109)

        at com.yandex.mobile.ads.impl.lo.a(SourceFile:44)

        at com.yandex.mobile.ads.impl.lb.a(SourceFile:96)

        at com.yandex.mobile.ads.impl.kl.run(SourceFile:124)

     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.ProtocolVersion" on path: DexPathList[[zip file "/data/app/ru.cmtt.dtf-xaTl8_Hvs5d0IqzxIQiOTg==/base.apk"],nativeLibraryDirectories=[/data/app/ru.cmtt.dtf-xaTl8_Hvs5d0IqzxIQiOTg==/lib/arm64, /system/lib64]]

        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)

        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)

        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)

        at com.yandex.mobile.ads.impl.lg.a(SourceFile:109) 

        at com.yandex.mobile.ads.impl.lo.a(SourceFile:44) 

        at com.yandex.mobile.ads.impl.lb.a(SourceFile:96) 

        at com.yandex.mobile.ads.impl.kl.run(SourceFile:124) 

Помогает добавление в AndroidManifest.xml 
`
<uses-library
            android:name="org.apache.http.legacy"
            android:required="false" />
`

**Comment by satsakul** [comment]
Спасибо. В ближайшее время исправим

**Comment by satsakul** [comment]
Исправлено в версии 2.74
