### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException: name == null

### ISSUE THREAD

**Issue by DEADMC** [yandexmobile/yandex-ads-sdk-android#45]
Краш словлен на:
**Девайс**: MI 8 Explorer Edition
**Android**: 8.1.0
**Версии либ**: 
com.yandex.ads.mediation:mobileads-mytarget:1.3.0
com.yandex.android:mobileads:2.100
com.yandex.android:mobmetricalib:3.6.4

Fatal Exception: java.lang.NullPointerException: name == null
       at java.lang.Thread.setName + 1128(Thread.java:1128)
       at java.lang.Thread.init + 411(Thread.java:411)
       at java.lang.Thread.(Thread.java:566)
       at com.yandex.mobile.ads.impl.dg.newThread + 31(dg.java:31)
       at java.util.concurrent.ThreadPoolExecutor$Worker.(ThreadPoolExecutor.java:631)
       at java.util.concurrent.ThreadPoolExecutor.addWorker + 945(ThreadPoolExecutor.java:945)
       at java.util.concurrent.ThreadPoolExecutor.execute + 1377(ThreadPoolExecutor.java:1377)
       at java.util.concurrent.Executors$DelegatedExecutorService.execute + 620(Executors.java:620)
       at com.yandex.mobile.ads.impl.km.a + 69(km.java:69)
       at com.yandex.mobile.ads.nativeads.t.a + 90(t.java:90)
       at com.yandex.mobile.ads.mediation.nativeads.s.a + 54(s.java:54)
       at com.yandex.mobile.ads.nativeads.t.a + 83(t.java:83)
       at com.yandex.mobile.ads.nativeads.t.a + 38(t.java:38)
       at com.yandex.mobile.ads.impl.qa.b + 38(qa.java:38)
       at com.yandex.mobile.ads.impl.ot$a.run + 105(ot.java:105)
       at android.os.Handler.handleCallback + 2(Handler.java:2)
       at android.os.Handler.dispatchMessage + 4(Handler.java:4)
       at android.os.Looper.loop + 139(Looper.java:139)
       at android.app.ActivityThread.main + 65(ActivityThread.java:65)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 11(RuntimeInit.java:11)
       at com.android.internal.os.ZygoteInit.main + 335(ZygoteInit.java:335)

**Comment by eugene-krivobokov** [comment]
@DEADMC , какая версия библиотеки?

**Comment by DEADMC** [comment]
@eugene-krivobokov добавил

**Comment by dmitryfisko** [comment]
Добрый день, извините за долгий ответ.
Как часто воспроизводится этот крэш?

**Comment by DEADMC** [comment]
Пока трудно судить, релиза с данной ошибкой еще не было.

**Comment by DEADMC** [comment]
Точно могу сказать что воспроизводится далеко не каждый раз

**Comment by dmitryfisko** [comment]
Добрый день, не удаётся воспроизвести проблему на тестовых приложениях
Приложите пожалуйста в тикет или пришлите на email (fisko@yandex-team.ru) сборку приложения на которой воспроизводится проблема

**Comment by satsakul** [comment]
Добрый день. Мы не смогли воспроизвести ошибку. Если она возникла у Вас в тесте и более не повторяется, предлагаю закрыть issue.
