### ISSUE TITLE
NPE in NativeLoadListener

### ISSUE THREAD

**Issue by nesterov-n** [yandexmobile/yandex-ads-sdk-android#7]
Версия 2.51
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void com.yandex.mobile.ads.nativeads.NativeAdLoader$OnLoadListener.onContentAdLoaded(com.yandex.mobile.ads.nativeads.NativeContentAd)' on a null object reference
       at com.yandex.mobile.ads.nativeads.NativeAdLoader$a$1.run(SourceFile:95)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7329)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```
Это происходит, если обнулить `listener` после отмены загрузки
```
adLoader.cancelLoading()
adLoader.setOnLoadListener(null)
```

**Comment by satsakul** [comment]
Спасибо. Мы уже знаем о проблеме. Она будет исправлена в ближайшей версии mobileads sdk 2.60
