### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by BlackDizel** [yandexmobile/yandex-ads-sdk-android#8]
периодически вылетает java.lang.NullPointerException:

```
FATAL EXCEPTION: pool-27-thread-1
                                                                  Process: <our project>, PID: 14759
                                                                  java.lang.NullPointerException: Attempt to invoke virtual method 'int com.yandex.mobile.ads.e.j()' on a null object reference
                                                                      at com.yandex.mobile.ads.f.b.b.<init>(SourceFile:52)
                                                                      at com.yandex.mobile.ads.f.b.a.<init>(SourceFile:29)
                                                                      at com.yandex.mobile.ads.y.a(SourceFile:54)
                                                                      at com.yandex.mobile.ads.t.a(SourceFile:7125)
                                                                      at com.yandex.mobile.ads.t$2.a(SourceFile:1116)
                                                                      at com.yandex.mobile.ads.aq.a(SourceFile:45)
                                                                      at com.yandex.mobile.ads.t.g(SourceFile:108)
                                                                      at com.yandex.mobile.ads.t$1.run(SourceFile:101)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                      at java.lang.Thread.run(Thread.java:818)
```

**Comment by satsakul** [comment]
Данная проблема была устранена в версии mobileads-2.60
